import { RecipeName } from '@/game/recipes/recipeTypes';
import type { EconomyPhase } from '@/game/finance';
import type { SalesCustomerDomain } from '@/game/sales/salesCustomers';
import { ResourceType } from '@/game/resources/resourceTypes';

/** Material Community icon names for inventory resources. */
export const RESOURCE_ICONS: Readonly<Record<ResourceType, string>> = {
  [ResourceType.Grain]: 'barley',
  [ResourceType.Bread]: 'bread-slice',
  [ResourceType.Water]: 'water',
  [ResourceType.Electricity]: 'lightning-bolt',
  [ResourceType.Sugar]: 'cube',
  [ResourceType.Coal]: 'fire',
  [ResourceType.Iron]: 'anvil',
  [ResourceType.Copper]: 'pipe',
  [ResourceType.Steel]: 'shield',
  [ResourceType.ElectricCircuits]: 'integrated-circuit-chip',
  [ResourceType.Bricks]: 'wall',
  [ResourceType.Cement]: 'bucket',
  [ResourceType.ReinforcedConcrete]: 'pillar',
  [ResourceType.ConstructionMaterials]: 'package',
  [ResourceType.Sand]: 'timer-sand',
  [ResourceType.Clay]: 'pot-mix',
  [ResourceType.Stone]: 'grave-stone',
  [ResourceType.Minerals]: 'crystal-ball',
  [ResourceType.Chemicals]: 'test-tube',
  [ResourceType.Fertilizer]: 'leaf',
  [ResourceType.Plastic]: 'bottle-soda',
  [ResourceType.Silicon]: 'memory',
  [ResourceType.Gold]: 'gold',
  [ResourceType.AdvancedComponents]: 'puzzle',
  [ResourceType.IndustrialMachines]: 'robot-industrial',
  [ResourceType.Cake]: 'cake',
  [ResourceType.PremiumCake]: 'cupcake',
  [ResourceType.Eggs]: 'egg',
  [ResourceType.Fruit]: 'fruit-citrus',
  [ResourceType.Meat]: 'food-steak',
  [ResourceType.MeatPie]: 'food-takeout-box',
  [ResourceType.Milk]: 'cup-water',
  [ResourceType.Wool]: 'spider-thread',
};

/** Shared Material Community icon names used by the app UI. */
export const APP_ICONS = {
  account: 'account-outline',
  achievements: 'trophy-outline',
  add: 'plus',
  back: 'chevron-left',
  bank: 'bank-outline',
  bid: 'gavel',
  building: 'factory',
  close: 'close',
  coin: 'circle-multiple-outline',
  collapse: 'chevron-up',
  currency: 'cash-multiple',
  delete: 'delete-outline',
  destroy: 'trash-can-outline',
  durability: 'shield-check-outline',
  economyPhase: 'chart-timeline-variant',
  efficiency: 'gauge',
  elapsedTime: 'timer-outline',
  expand: 'chevron-down',
  expired: 'timer-off-outline',
  facilityAnimalFarm: 'cow',
  facilityBakery: 'toaster-oven',
  facilityFarm: 'tractor',
  facilityMine: 'pickaxe',
  facilityPowerPlant: 'factory',
  facilityUtilityWorks: 'transmission-tower',
  facilityWaterWell: 'water-well',
  fastForward: 'fast-forward',
  financeHistory: 'text-box-outline',
  fulfilled: 'check-circle-outline',
  globalMarket: 'earth',
  help: 'book-open-variant',
  logout: 'logout',
  localMarket: 'storefront-outline',
  marketAutoBuy: 'cart-arrow-down',
  marketAutoSell: 'cash-sync',
  marketBalanced: 'minus',
  marketBuy: 'cart-outline',
  marketFlowToGlobal: 'arrow-right',
  marketFlowToLocal: 'arrow-left',
  marketGlobalPrice: 'earth',
  marketLocalPrice: 'cash-multiple',
  regionalMarket: 'city-variant',
  marketRegionalPrice: 'city-variant-outline',
  marketSell: 'cash-fast',
  marketShare: 'chart-pie',
  marketTrendDown: 'arrow-down',
  marketTrendUp: 'arrow-up',
  minus: 'minus',
  next: 'chevron-right',
  openOrders: 'format-list-numbered',
  output: 'package-variant',
  package: 'package-variant-closed',
  pause: 'pause',
  pencil: 'pencil',
  play: 'play-circle-outline',
  prestige: 'trophy-outline',
  production: 'cog-outline',
  purchasingPower: 'cash-multiple',
  quality: 'star',
  relationship: 'handshake-outline',
  rejected: 'close-circle-outline',
  research: 'flask-outline',
  reset: 'delete-outline',
  resume: 'play',
  salesOrders: 'handshake-outline',
  settings: 'cog-outline',
  shield: 'shield-crown-outline',
  speed: 'trending-up',
  staffing: 'account-group-outline',
  upgrade: 'arrow-up-bold-circle-outline',
  work: 'progress-clock',
} as const;

export const ECONOMY_PHASE_ICONS: Readonly<Record<EconomyPhase, string>> = {
  crash: 'weather-lightning-rainy',
  recession: 'weather-rainy',
  stable: 'weather-partly-cloudy',
  expansion: 'weather-sunny',
  boom: 'weather-sunny-alert',
};

export const SALES_CUSTOMER_TYPE_ICONS = {
  'private-customer': 'account-outline',
  'retail-chain': 'storefront-outline',
  'construction-contractor': 'hammer-wrench',
  'industrial-enterprise': 'factory',
  'utility-operator': 'transmission-tower',
  'government-procurement': 'bank-outline',
} as const;

export const SALES_CUSTOMER_DOMAIN_ICONS: Readonly<Record<SalesCustomerDomain, string>> = {
  food: 'food-apple-outline',
  'raw-materials': 'pickaxe',
  'industrial-inputs': 'factory',
  'construction-materials': 'crane',
  electronics: 'chip',
  utilities: 'transmission-tower',
};

/** Shared Material Community icon names for recipe presentation. */
export const RECIPE_ICONS: Readonly<Record<RecipeName, string>> = {
  [RecipeName.GrowGrain]: 'sprout-outline',
  [RecipeName.BakeBread]: 'stove',
  [RecipeName.ProduceWater]: 'water-well',
  [RecipeName.ProduceElectricity]: 'generator-stationary',
  [RecipeName.GrowSugar]: 'sprout',
  [RecipeName.GrowFruit]: 'fruit-cherries',
  [RecipeName.RaiseCattle]: 'cow',
  [RecipeName.RaiseSheep]: 'sheep',
  [RecipeName.RaiseChicken]: 'food-drumstick-outline',
  [RecipeName.MineIron]: 'pickaxe',
  [RecipeName.MineCoal]: 'mine',
  [RecipeName.MineCopper]: 'pipe-wrench',
  [RecipeName.QuarrySand]: 'shovel',
  [RecipeName.QuarryClay]: 'pot-mix',
  [RecipeName.QuarryStone]: 'hammer',
  [RecipeName.QuarryMinerals]: 'crystal-ball',
  [RecipeName.MineGold]: 'treasure-chest',
  [RecipeName.ProduceSteel]: 'hammer-wrench',
  [RecipeName.ProduceElectricCircuits]: 'chip',
  [RecipeName.ProduceChemicals]: 'flask-outline',
  [RecipeName.SynthesizeFertilizer]: 'flask-plus',
  [RecipeName.ProducePlastic]: 'recycle',
  [RecipeName.ProduceSilicon]: 'diamond-stone',
  [RecipeName.ProduceAdvancedComponents]: 'cog-outline',
  [RecipeName.AssembleIndustrialMachines]: 'factory',
  [RecipeName.ProduceBricks]: 'wall',
  [RecipeName.ProduceCement]: 'bowl-mix',
  [RecipeName.ProduceReinforcedConcrete]: 'office-building-outline',
  [RecipeName.ProduceConstructionMaterials]: 'package-variant-closed',
  [RecipeName.BakeCake]: 'toaster-oven',
  [RecipeName.BakePremiumCake]: 'cake-layered',
  [RecipeName.BakeMeatPie]: 'pot-steam',
  [RecipeName.ManualPumping]: 'hand-water',
  [RecipeName.ElectricPumping]: 'water-pump',
  [RecipeName.CoalPower]: 'transmission-tower',
  [RecipeName.SolarPower]: 'solar-power-variant-outline',
};
