import { RecipeName } from '@/game/recipes/recipeTypes';
import { ResourceType } from '@/game/resources/resourceTypes';

/** Shared Material Community icon names used by the app UI. */
export const APP_ICONS = {
  add: 'plus',
  account: 'account-outline',
  achievements: 'trophy-outline',
  back: 'chevron-left',
  bank: 'bank-outline',
  building: 'factory',
  collapse: 'chevron-up',
  coin: 'circle-multiple-outline',
  contracts: 'handshake-outline',
  currency: 'cash-multiple',
  delete: 'delete-outline',
  destroy: 'trash-can-outline',
  expand: 'chevron-down',
  elapsedTime: 'timer-outline',
  fastForward: 'fast-forward',
  facilityBakery: 'bread-slice-outline',
  facilityFarm: 'tractor',
  facilityMine: 'pickaxe',
  facilityPowerPlant: 'factory',
  facilityUtilityWorks: 'flash-outline',
  facilityWaterWell: 'water-well',
  financeHistory: 'text-box-outline',
  help: 'book-open-variant',
  logout: 'logout',
  localMarket: 'storefront-outline',
  regionalMarket: 'city-variant-outline',
  minus: 'minus',
  next: 'chevron-right',
  package: 'package-variant-closed',
  pencil: 'pencil',
  play: 'play-circle-outline',
  production: 'cog-outline',
  prestige: 'trophy-outline',
  quality: 'star',
  reset: 'delete-outline',
  research: 'flask-outline',
  settings: 'cog-outline',
  shield: 'shield-crown-outline',
  globalMarket: 'earth',
  marketAutoBuy: 'cart-arrow-down',
  marketAutoSell: 'cash-sync',
  marketBalanced: 'minus',
  marketBuy: 'cart-outline',
  marketFlowToGlobal: 'arrow-right',
  marketFlowToLocal: 'arrow-left',
  marketGlobalPrice: 'earth',
  marketLocalPrice: 'cash-multiple',
  marketRegionalPrice: 'city-variant-outline',
  marketSell: 'cash-fast',
  marketTrendDown: 'arrow-down',
  marketTrendUp: 'arrow-up',
  close: 'close',
  speed: 'trending-up',
  output: 'package-variant',
  upgrade: 'arrow-up-bold-circle-outline',
  staffing: 'account-group-outline',
  efficiency: 'gauge',
  pause: 'pause',
  resume: 'play',
  work: 'progress-clock',
} as const;

/** Shared Material Community icon names for recipe presentation. */
export const RECIPE_ICONS: Readonly<Record<RecipeName, string>> = {
  [RecipeName.GrowGrain]: 'sprout-outline',
  [RecipeName.BakeBread]: 'bread-slice-outline',
  [RecipeName.ProduceWater]: 'water-outline',
  [RecipeName.ProduceElectricity]: 'flash-outline',
  [RecipeName.GrowSugar]: 'candy-outline',
  [RecipeName.MineIron]: 'pickaxe',
  [RecipeName.MineCoal]: 'pickaxe',
  [RecipeName.MineCopper]: 'pickaxe',
  [RecipeName.QuarrySand]: 'image-filter-hdr',
  [RecipeName.QuarryClay]: 'image-filter-hdr',
  [RecipeName.QuarryStone]: 'image-filter-hdr',
  [RecipeName.ProduceSteel]: 'hammer-wrench',
  [RecipeName.ProduceElectricCircuits]: 'chip',
  [RecipeName.ProduceBricks]: 'wall',
  [RecipeName.ProduceCement]: 'mixer',
  [RecipeName.ProduceReinforcedConcrete]: 'office-building-outline',
  [RecipeName.ProduceConstructionMaterials]: 'package-variant-closed',
  [RecipeName.BakeCake]: 'cake-variant-outline',
  [RecipeName.ManualPumping]: 'water-pump',
  [RecipeName.ElectricPumping]: 'water-pump',
  [RecipeName.CoalPower]: 'transmission-tower',
  [RecipeName.SolarPower]: 'solar-power-variant-outline',
};

/** Shared emoji resource symbols used in compact inventory and recipe labels. */
export const RESOURCE_ICONS: Readonly<Record<ResourceType, string>> = {
  [ResourceType.Grain]: '🌾',
  [ResourceType.Bread]: '🍞',
  [ResourceType.Water]: '💧',
  [ResourceType.Electricity]: '⚡',
  [ResourceType.Sugar]: '🍬',
  [ResourceType.Coal]: '🪨',
  [ResourceType.Iron]: '⛓️',
  [ResourceType.Copper]: '🟠',
  [ResourceType.Steel]: '🔩',
  [ResourceType.ElectricCircuits]: '🔌',
  [ResourceType.Bricks]: '🧱',
  [ResourceType.Cement]: '🏗️',
  [ResourceType.ReinforcedConcrete]: '🏢',
  [ResourceType.ConstructionMaterials]: '🏗️',
  [ResourceType.Sand]: '🏜️',
  [ResourceType.Clay]: '🟫',
  [ResourceType.Stone]: '⛰️',
  [ResourceType.Cake]: '🍰',
};
