import type { EconomyPhase } from '@/game/finance';
import type { ResourceType } from '@/game/resources';
import { SALES_CUSTOMER_DOMAIN_PROFILES, SALES_ECONOMY_MULTIPLIERS, SALES_ORDER_BASE_ACQUISITION_CHANCE_PER_MINUTE, SALES_ORDER_DURATION_MS, SALES_ORDER_MAXIMUM_QUANTITY, SALES_ORDER_MINIMUM_QUANTITY, SALES_ORDER_PENDING_PENALTY_PER_OPEN_ORDER, SALES_ORDER_PRESTIGE_DISCOVERY_SCALE } from './salesConstants';
import { SALES_CUSTOMER_CATALOGUE_VERSION, SALES_CUSTOMER_RELATIONSHIP, SALES_CUSTOMER_WORLD_SEED, advanceSalesCustomerRelationship, calculateSalesCustomerRelationshipBaseline, createSalesCustomerState, getSalesCustomerCatalogue, getSalesResourceProfile, type SalesCustomerDefinition, type SalesCustomerState } from './salesCustomers';

export type SalesOrderStatus = 'offered' | 'fulfilled' | 'rejected' | 'expired';
export type SalesOrder = { id: string; status: SalesOrderStatus; customerId: string; customerName: string; customerDomain: SalesCustomerDefinition['domain']; resourceType: ResourceType; quantity: number; globalReferenceUnitPrice: number; bidUnitPrice: number; premiumPercent: number; reward: number; offeredAtGameTimeMs: number; expiresAtGameTimeMs: number; fulfilledAtGameTimeMs?: number; rejectedAtGameTimeMs?: number; expiredAtGameTimeMs?: number };
export type SalesOrdersSnapshot = { offered: SalesOrder[]; completed: SalesOrder[]; customerStates: SalesCustomerState[]; nextOrderNumber: number; worldSeed: string; catalogueVersion: number };
export type SalesOrderGenerationInput = { currentGameTimeMs: number; maximumOpenOrders: number; companyPrestige: number; economyPhase: EconomyPhase; inventoryByResource: Readonly<Record<ResourceType, number>>; globalPrices: Readonly<Record<ResourceType, number>>; candidateResourceTypes: readonly ResourceType[]; getResourceWeight: (resourceType: ResourceType) => number; bidResearchMultiplier: number };

const clamp = (value: number, minimum: number, maximum: number): number => Math.max(minimum, Math.min(maximum, value));
function roll(seed: string): number { let hash = 2_166_136_261; for (let index = 0; index < seed.length; index += 1) { hash ^= seed.charCodeAt(index); hash = Math.imul(hash, 16_777_619); } return (hash >>> 0) / 4_294_967_296; }
function pickWeighted<T>(entries: readonly { value: T; weight: number }[], seed: string): T | null { const total = entries.reduce((sum, entry) => sum + Math.max(0, entry.weight), 0); if (total <= 0) return null; let remaining = roll(seed) * total; for (const entry of entries) { remaining -= Math.max(0, entry.weight); if (remaining <= 0) return entry.value; } return entries[entries.length - 1]?.value ?? null; }
function cloneOrder(order: SalesOrder): SalesOrder { return { ...order }; }
function cloneState(state: SalesCustomerState): SalesCustomerState { return { ...state }; }

export function calculateSalesOrderAcquisitionChance(input: { openOrderCount: number; companyPrestige: number; economyPhase: EconomyPhase; hasEligibleInventory: boolean }): number {
  if (!input.hasEligibleInventory) return 0;
  const discovery = 0.45 + Math.max(0, input.companyPrestige) / (Math.max(0, input.companyPrestige) + SALES_ORDER_PRESTIGE_DISCOVERY_SCALE);
  const pending = Math.max(0.08, 1 - input.openOrderCount * SALES_ORDER_PENDING_PENALTY_PER_OPEN_ORDER);
  return clamp(SALES_ORDER_BASE_ACQUISITION_CHANCE_PER_MINUTE * discovery * pending * SALES_ECONOMY_MULTIPLIERS[input.economyPhase].acquisition, 0, 0.95);
}
export function calculateSalesOrderEstimatedWaitMinutes(chance: number): number { return chance > 0 ? 1 / chance : 0; }
export function calculateSalesOrderMarketComparison(order: Pick<SalesOrder, 'quantity' | 'reward'>, normalMarketUnitPrice: number): { normalSaleValue: number; gain: number; gainPercent: number } { const normalSaleValue = order.quantity * normalMarketUnitPrice; const gain = order.reward - normalSaleValue; return { normalSaleValue, gain, gainPercent: normalSaleValue > 0 ? gain / normalSaleValue * 100 : 0 }; }

export class SalesOrders {
  private offered: SalesOrder[] = []; private completed: SalesOrder[] = []; private customerStates: SalesCustomerState[] = []; private nextOrderNumber = 1; private worldSeed = SALES_CUSTOMER_WORLD_SEED; private catalogueVersion = SALES_CUSTOMER_CATALOGUE_VERSION;
  constructor(snapshot?: SalesOrdersSnapshot) { if (snapshot) this.restore(snapshot); }
  getCustomerCatalogue(): SalesCustomerDefinition[] { return getSalesCustomerCatalogue(this.worldSeed, this.catalogueVersion); }
  getOfferedOrders(): SalesOrder[] { return this.offered.map(cloneOrder); }
  getCompletedOrders(): SalesOrder[] { return this.completed.map(cloneOrder); }
  getOfferedOrder(id: string): SalesOrder | null { const order = this.offered.find((candidate) => candidate.id === id); return order ? cloneOrder(order) : null; }
  getCustomerStates(): SalesCustomerState[] { return this.customerStates.map(cloneState); }
  getCustomerState(customerId: string, currentGameTimeMs: number, companyPrestige: number): SalesCustomerState { const customer = this.getCustomerCatalogue().find((candidate) => candidate.id === customerId); const state = this.customerStates.find((candidate) => candidate.customerId === customerId); if (!customer) return createSalesCustomerState(customerId, 0, currentGameTimeMs); return advanceSalesCustomerRelationship(state ?? createSalesCustomerState(customerId, calculateSalesCustomerRelationshipBaseline(customer, companyPrestige), currentGameTimeMs), customer, companyPrestige, currentGameTimeMs); }
  createDevelopmentOrderForResource(resourceType: ResourceType, quantity: number, globalReferenceUnitPrice: number, maximumOpenOrders: number, currentGameTimeMs: number, companyPrestige: number): SalesOrder | null {
    if (!Number.isInteger(quantity) || quantity < SALES_ORDER_MINIMUM_QUANTITY || quantity > SALES_ORDER_MAXIMUM_QUANTITY || this.offered.length >= maximumOpenOrders || !Number.isFinite(globalReferenceUnitPrice) || globalReferenceUnitPrice <= 0) return null;
    const profile = getSalesResourceProfile(resourceType); const customer = this.getCustomerCatalogue().find((candidate) => candidate.domain === profile.domain); if (!customer) return null;
    const state = this.getCustomerState(customer.id, currentGameTimeMs, companyPrestige); const bidUnitPrice = globalReferenceUnitPrice * (0.95 + state.relationship / 100 * 0.15); const order: SalesOrder = { id: `sales-order-${this.nextOrderNumber}`, status: 'offered', customerId: customer.id, customerName: customer.name, customerDomain: customer.domain, resourceType, quantity, globalReferenceUnitPrice, bidUnitPrice, premiumPercent: bidUnitPrice / globalReferenceUnitPrice * 100 - 100, reward: quantity * bidUnitPrice, offeredAtGameTimeMs: currentGameTimeMs, expiresAtGameTimeMs: currentGameTimeMs + SALES_ORDER_DURATION_MS }; this.nextOrderNumber += 1; this.offered.push(order); return cloneOrder(order);
  }
  advanceTime(input: SalesOrderGenerationInput): { ordersCreated: number; ordersExpired: SalesOrder[]; acquisitionChance: number } {
    this.advanceRelationships(input.currentGameTimeMs, input.companyPrestige);
    const ordersExpired = this.expireOrders(input.currentGameTimeMs, input.companyPrestige);
    const eligibleResources = input.candidateResourceTypes.filter((resourceType) => input.inventoryByResource[resourceType] >= getSalesResourceProfile(resourceType).standardOrderLot && Number.isFinite(input.globalPrices[resourceType]) && input.globalPrices[resourceType] > 0);
    const acquisitionChance = calculateSalesOrderAcquisitionChance({ openOrderCount: this.offered.length, companyPrestige: input.companyPrestige, economyPhase: input.economyPhase, hasEligibleInventory: eligibleResources.length > 0 });
    if (this.offered.length >= input.maximumOpenOrders || eligibleResources.length === 0 || roll(`acquire:${this.worldSeed}:${this.nextOrderNumber}:${input.currentGameTimeMs}`) >= acquisitionChance) return { ordersCreated: 0, ordersExpired, acquisitionChance };
    const resourceType = pickWeighted(eligibleResources.map((value) => ({ value, weight: Math.max(0.01, input.getResourceWeight(value)) })), `resource:${this.nextOrderNumber}`);
    if (!resourceType) return { ordersCreated: 0, ordersExpired, acquisitionChance };
    const profile = getSalesResourceProfile(resourceType); const customers = this.getCustomerCatalogue().filter((customer) => customer.domain === profile.domain);
    const customer = pickWeighted(customers.map((value) => ({ value, weight: value.marketShare * SALES_CUSTOMER_DOMAIN_PROFILES[value.domain].frequency })), `customer:${this.nextOrderNumber}`);
    if (!customer) return { ordersCreated: 0, ordersExpired, acquisitionChance };
    const state = this.getCustomerState(customer.id, input.currentGameTimeMs, input.companyPrestige); const domain = SALES_CUSTOMER_DOMAIN_PROFILES[customer.domain]; const basePrice = input.globalPrices[resourceType];
    const relationshipEffect = 0.88 + state.relationship / 100 * 0.28; const prestigeEffect = 0.94 + Math.max(0, input.companyPrestige) / (Math.max(0, input.companyPrestige) + 150) * 0.12;
    const bidUnitPrice = Math.max(0.01, basePrice * customer.bidMultiplier * relationshipEffect * prestigeEffect * SALES_ECONOMY_MULTIPLIERS[input.economyPhase].bid * input.bidResearchMultiplier); const target = domain.targetOrderValue[0] + (domain.targetOrderValue[1] - domain.targetOrderValue[0]) * roll(`value:${this.nextOrderNumber}`); const lot = getSalesResourceProfile(resourceType).standardOrderLot; const quantity = clamp(Math.ceil(target / bidUnitPrice / lot) * lot, Math.max(lot, SALES_ORDER_MINIMUM_QUANTITY), SALES_ORDER_MAXIMUM_QUANTITY);
    const order: SalesOrder = { id: `sales-order-${this.nextOrderNumber}`, status: 'offered', customerId: customer.id, customerName: customer.name, customerDomain: customer.domain, resourceType, quantity, globalReferenceUnitPrice: basePrice, bidUnitPrice, premiumPercent: bidUnitPrice / basePrice * 100 - 100, reward: quantity * bidUnitPrice, offeredAtGameTimeMs: input.currentGameTimeMs, expiresAtGameTimeMs: input.currentGameTimeMs + SALES_ORDER_DURATION_MS };
    this.nextOrderNumber += 1; this.offered.push(order); return { ordersCreated: 1, ordersExpired, acquisitionChance };
  }
  fulfill(id: string, fulfilledAtGameTimeMs: number, companyPrestige: number): SalesOrder | null { const index = this.offered.findIndex((order) => order.id === id); if (index < 0) return null; const [order] = this.offered.splice(index, 1); const fulfilled = { ...order, status: 'fulfilled' as const, fulfilledAtGameTimeMs }; this.completed.unshift(fulfilled); this.applyRelationship(fulfilled.customerId, companyPrestige, fulfilledAtGameTimeMs, SALES_CUSTOMER_RELATIONSHIP.fulfilmentBaseGain * SALES_CUSTOMER_DOMAIN_PROFILES[fulfilled.customerDomain].relationshipGainMultiplier * (1 + Math.max(0, fulfilled.premiumPercent) / 200), 'fulfilled'); return cloneOrder(fulfilled); }
  reject(id: string, rejectedAtGameTimeMs: number): SalesOrder | null { const index = this.offered.findIndex((order) => order.id === id); if (index < 0) return null; const [order] = this.offered.splice(index, 1); const rejected = { ...order, status: 'rejected' as const, rejectedAtGameTimeMs }; this.completed.unshift(rejected); return cloneOrder(rejected); }
  clone(): SalesOrders { return SalesOrders.fromSnapshot(this.toSnapshot()); }
  toSnapshot(): SalesOrdersSnapshot { return { offered: this.getOfferedOrders(), completed: this.getCompletedOrders(), customerStates: this.getCustomerStates(), nextOrderNumber: this.nextOrderNumber, worldSeed: this.worldSeed, catalogueVersion: this.catalogueVersion }; }
  static fromSnapshot(snapshot: SalesOrdersSnapshot): SalesOrders { return new SalesOrders(snapshot); }
  private advanceRelationships(currentGameTimeMs: number, companyPrestige: number): void { const catalogue = new Map(this.getCustomerCatalogue().map((customer) => [customer.id, customer])); this.customerStates = this.customerStates.map((state) => { const customer = catalogue.get(state.customerId); return customer ? advanceSalesCustomerRelationship(state, customer, companyPrestige, currentGameTimeMs) : state; }); }
  private expireOrders(currentGameTimeMs: number, companyPrestige: number): SalesOrder[] { const expired: SalesOrder[] = []; const remaining: SalesOrder[] = []; for (const order of this.offered) { if (order.expiresAtGameTimeMs > currentGameTimeMs) { remaining.push(order); continue; } const expiredOrder = { ...order, status: 'expired' as const, expiredAtGameTimeMs: currentGameTimeMs }; this.completed.unshift(expiredOrder); expired.push(cloneOrder(expiredOrder)); this.applyRelationship(order.customerId, companyPrestige, currentGameTimeMs, -SALES_CUSTOMER_RELATIONSHIP.expiryLoss, 'expired'); } this.offered = remaining; return expired; }
  private applyRelationship(customerId: string, companyPrestige: number, currentGameTimeMs: number, adjustment: number, outcome: 'fulfilled' | 'expired'): void { const customer = this.getCustomerCatalogue().find((candidate) => candidate.id === customerId); if (!customer) return; const current = this.getCustomerState(customerId, currentGameTimeMs, companyPrestige); const next = { ...current, relationship: clamp(current.relationship + adjustment, 0, SALES_CUSTOMER_RELATIONSHIP.maximum), fulfilledOrderCount: current.fulfilledOrderCount + (outcome === 'fulfilled' ? 1 : 0), expiredOrderCount: current.expiredOrderCount + (outcome === 'expired' ? 1 : 0) }; const index = this.customerStates.findIndex((state) => state.customerId === customerId); if (index < 0) this.customerStates.push(next); else this.customerStates[index] = next; }
  private restore(snapshot: SalesOrdersSnapshot): void { this.offered = Array.isArray(snapshot.offered) ? snapshot.offered.filter((order) => order.status === 'offered').map(cloneOrder) : []; this.completed = Array.isArray(snapshot.completed) ? snapshot.completed.filter((order) => order.status !== 'offered').map(cloneOrder) : []; this.customerStates = Array.isArray(snapshot.customerStates) ? snapshot.customerStates.map(cloneState) : []; this.nextOrderNumber = Number.isInteger(snapshot.nextOrderNumber) && snapshot.nextOrderNumber > 0 ? snapshot.nextOrderNumber : 1; this.worldSeed = typeof snapshot.worldSeed === 'string' && snapshot.worldSeed.length > 0 ? snapshot.worldSeed : SALES_CUSTOMER_WORLD_SEED; this.catalogueVersion = Number.isInteger(snapshot.catalogueVersion) && snapshot.catalogueVersion > 0 ? snapshot.catalogueVersion : SALES_CUSTOMER_CATALOGUE_VERSION; }
}
