import { StyleSheet } from 'react-native';

import { colors } from '@/theme';

export const styles = StyleSheet.create({
  adminContractControls: { gap: 8 },
  adminContractAmountInput: { backgroundColor: colors.surface },
  adminSuccessMessage: { color: colors.primary, fontWeight: '700' },
  activeNavigationItem: { backgroundColor: colors.paleGreen },
  activeNavigationText: { color: colors.primary, fontWeight: '700' },
  avatar: { backgroundColor: '#D9EDE5' },
  balanceInline: { alignItems: 'center', flexDirection: 'row', gap: 8 },
  balanceInlineValue: { color: colors.onDark, fontSize: 20, fontWeight: '700' },
  balanceValue: { color: colors.charcoal, fontSize: 36, fontWeight: '700', lineHeight: 42 },
  bottomNavigation: {
    backgroundColor: colors.surface,
    flexDirection: 'row',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  cardContent: { gap: 8 },
  cardDescription: { color: colors.muted, lineHeight: 21 },
  cardKicker: {
    color: colors.primary,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1,
  },
  content: { gap: 12, padding: 20, paddingBottom: 28 },
  constructionYardCard: { backgroundColor: colors.softBackground },
  constructionYardDialog: { maxHeight: '88%' },
  constructionYardDialogContent: { flexShrink: 1 },
  constructionYardFunds: { color: colors.primary, fontWeight: '700', marginTop: 12 },
  constructionYardList: { gap: 12, paddingVertical: 16 },
  constructionYardListViewport: { flexShrink: 1 },
  constructionYardRecipe: { color: colors.muted, lineHeight: 20, marginTop: 4 },
  constructionYardRecipeLabel: { color: colors.charcoal, fontWeight: '700', marginTop: 8 },
  customerPipelineOverflow: { backgroundColor: colors.error, bottom: 0, left: 0, position: 'absolute', top: 0 },
  customerPipelineProgressBar: { height: 8 },
  customerPipelineProgressTrack: { borderRadius: 6, height: 8, overflow: 'hidden', position: 'relative' },
  dialogDescription: { color: colors.muted, lineHeight: 21 },
  dialogSummary: { gap: 8, marginTop: 16 },
  dialogSectionHeading: { marginTop: 16, marginBottom: 4 },
  featureCard: { backgroundColor: colors.surface },
  facilityActions: { alignItems: 'flex-end', marginTop: 4 },
  facilityRecipeControls: { gap: 8, marginTop: 8 },
  facilityResourceArrow: { color: colors.muted, fontSize: 20, marginHorizontal: 4 },
  facilityResourceEmpty: { color: colors.muted },
  facilityResourceGroup: { flex: 1, gap: 4 },
  facilityResourceItems: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  facilityResourceLabel: { color: colors.muted, fontSize: 12, fontWeight: '700' },
  facilityResourceSummary: { alignItems: 'center', flexDirection: 'row', marginTop: 12 },
  facilityResourceValue: { color: colors.charcoal, fontWeight: '700' },
  facilityStaffingControls: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginTop: 4 },
  facilityStaffingDetail: { color: colors.muted, fontSize: 12 },
  facilityStaffingSummary: { alignItems: 'center', flex: 1 },
  facilityStaffingValue: { color: colors.charcoal, fontWeight: '700' },
  facilityTitle: { color: colors.charcoal, fontWeight: '700' },
  facilityUpgradeControls: { gap: 8, marginTop: 8 },
  facilityUpgradeSummary: { color: colors.muted, marginTop: 4 },
  header: { backgroundColor: colors.primary },
  headerActions: { alignItems: 'center', flexDirection: 'row' },
  headerElapsedTime: { alignItems: 'center', flexDirection: 'row', gap: 3, minHeight: 44, paddingHorizontal: 4 },
  headerElapsedTimeValue: { color: colors.onDark, fontSize: 13, fontWeight: '700' },
  inventoryHeading: { color: colors.charcoal, marginTop: 8 },
  marketActionButton: { margin: 0 },
  marketAutomationInput: { marginBottom: 8 },
  marketActions: { alignItems: 'center', flexDirection: 'row', gap: 4, justifyContent: 'flex-end' },
  marketCard: { backgroundColor: colors.surface },
  marketCardContent: { gap: 10 },
  marketInventory: { color: colors.marketGreen, fontSize: 21, fontWeight: '800' },
  marketMetric: { gap: 2 },
  marketMetricColumn: { flex: 1, gap: 10 },
  marketMetricFlowColumn: { flex: 0.85 },
  marketMetricLabel: { color: colors.muted, fontSize: 10, fontWeight: '700', textTransform: 'uppercase' },
  marketMetricValue: { fontSize: 13, fontWeight: '700' },
  marketMetricValueRow: { alignItems: 'center', flexDirection: 'row', gap: 3 },
  marketMetrics: { flexDirection: 'row', gap: 10 },
  marketResourceHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  marketResourceName: { color: colors.charcoal, fontWeight: '700' },
  marketSlider: { marginBottom: 14, minHeight: 62 },
  marketSliderTouchArea: { height: 34, justifyContent: 'center', position: 'relative' },
  marketSliderLabel: { color: colors.muted, fontSize: 11, fontWeight: '700', marginTop: 3 },
  marketSliderLabelActive: { color: colors.primary },
  marketSliderLabels: { flexDirection: 'row', justifyContent: 'space-between' },
  marketSliderStep: { alignItems: 'center', minHeight: 28, minWidth: 36 },
  marketSliderMarker: { backgroundColor: colors.muted, borderRadius: 4, height: 8, width: 8 },
  marketSliderMarkerActive: { backgroundColor: colors.primary, height: 10, width: 10 },
  marketSliderThumb: { backgroundColor: colors.marketAutomationActive, borderRadius: 10, height: 20, marginLeft: -10, position: 'absolute', top: 7, width: 20 },
  marketSliderTrack: { backgroundColor: '#D4DDD9', borderRadius: 3, height: 6, left: 0, position: 'absolute', right: 0, top: 14 },
  marketSliderFill: { backgroundColor: colors.primary, borderRadius: 3, height: 6, left: 0, position: 'absolute', top: 14 },
  inventoryQualityValue: { alignItems: 'center', flexDirection: 'row', gap: 4 },
  navigationItem: {
    alignItems: 'center',
    borderRadius: 12,
    flex: 1,
    gap: 2,
    minHeight: 52,
    justifyContent: 'center',
  },
  navigationLabel: { color: colors.muted, fontSize: 12, fontWeight: '600' },
  navigationSymbol: {
    color: colors.muted,
    fontSize: 20,
    fontWeight: '700',
    lineHeight: 22,
  },
  detailRow: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 62,
    paddingHorizontal: 16,
  },
  detailValue: { color: colors.muted },
  productionError: { color: colors.error, lineHeight: 20, marginTop: 12 },
  productionPercent: { color: colors.muted, fontSize: 12 },
  productionProgress: { gap: 6, marginTop: 12 },
  productionProgressBar: { borderRadius: 6, height: 8 },
  productionProgressHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  productionTimeLeft: { alignSelf: 'flex-end', color: colors.muted, fontSize: 12, marginBottom: 8 },
  productionValuePlaceholder: { color: colors.primary, fontSize: 12, fontWeight: '700' },
  prestigeInline: { alignItems: 'center', flexDirection: 'row', gap: 3, minHeight: 44, paddingHorizontal: 4 },
  prestigeInlineValue: { color: colors.onDark, fontSize: 14, fontWeight: '700' },
  profileButton: { borderRadius: 22, padding: 2 },
  safeArea: { backgroundColor: colors.primary, flex: 1 },
  salesAvailability: { color: colors.muted, fontSize: 12 },
  salesCapacity: { color: colors.primary, fontSize: 13, fontWeight: '700' },
  salesActions: { flexDirection: 'row', gap: 8 },
  salesContractHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', paddingRight: 28 },
  salesRejectButton: { position: 'absolute', right: 2, top: 2 },
  salesFilterButton: { flex: 1 },
  salesFilters: { flexDirection: 'row', gap: 8 },
  salesReward: { color: colors.primary, fontSize: 20, fontWeight: '700' },
  screen: { backgroundColor: colors.softBackground, flex: 1 },
  sectionEyebrow: {
    color: colors.primary,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.1,
  },
  sectionHeading: { gap: 4, marginBottom: 4 },
  sectionSubtitle: { color: colors.muted, lineHeight: 20 },
  topBar: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 64,
    paddingHorizontal: 20,
  },
  transactionCost: { color: colors.error, fontWeight: '700' },
  transactionDetails: { flex: 1, gap: 2, paddingRight: 12 },
  transactionIcon: { alignItems: 'center', borderRadius: 20, height: 40, justifyContent: 'center', marginRight: 12, width: 40 },
  transactionIconCost: { backgroundColor: '#FBE9E7' },
  transactionIconIncome: { backgroundColor: colors.paleGreen },
  transactionIncome: { color: colors.primary, fontWeight: '700' },
  workMetric: { alignItems: 'center', flexDirection: 'row', gap: 4 },
  workMetricIcon: { color: colors.muted },
});
