import { StyleSheet } from 'react-native';

import { colors } from '@/theme';

export const styles = StyleSheet.create({
  adminContractControls: { gap: 8 },
  adminMoneyActions: { flexDirection: 'row', gap: 8 },
  adminContractAmountInput: { backgroundColor: colors.surface },
  adminSuccessMessage: { color: colors.primary, fontWeight: '700' },
  activeNavigationItem: { backgroundColor: colors.paleGreen },
  activeNavigationText: { color: colors.primary, fontWeight: '700' },
  avatar: { backgroundColor: '#D9EDE5' },
  balanceInline: { alignItems: 'center', flexDirection: 'row', gap: 8 },
  balanceAmount: { alignItems: 'center', flexDirection: 'row', gap: 8 },
  balanceInlineValue: { color: colors.onDark, fontSize: 20, fontWeight: '700' },
  balanceValue: { color: colors.charcoal, fontSize: 36, fontWeight: '700', lineHeight: 42 },
  bottomNavigation: {
    backgroundColor: colors.surface,
    flexDirection: 'row',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  cardContent: { gap: 8 },
  cardDescription: { color: colors.muted, lineHeight: 21 },
  cardKicker: {
    color: colors.primary,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1,
  },
  content: { gap: 12, padding: 20, paddingBottom: 28 },
  constructionYardCard: { backgroundColor: colors.softBackground },
  constructionYardCardDisabled: { opacity: 0.45 },
  constructionYardDialog: { maxHeight: '88%' },
  constructionYardDialogContent: { flexShrink: 1 },
  constructionYardFunds: { color: colors.primary, fontWeight: '700', marginTop: 12 },
  constructionYardList: { gap: 12, paddingVertical: 16 },
  constructionYardListViewport: { flexShrink: 1 },
  constructionYardRecipe: { color: colors.muted, lineHeight: 20, marginTop: 4 },
  constructionYardRecipeLabel: { color: colors.charcoal, fontWeight: '700', marginTop: 8 },
  customerPipelineOverflow: { backgroundColor: colors.error, bottom: 0, left: 0, position: 'absolute', top: 0 },
  customerPipelineProgressBar: { height: 8 },
  customerPipelineProgressTrack: { borderRadius: 6, height: 8, overflow: 'hidden', position: 'relative' },
  dialogDescription: { color: colors.muted, lineHeight: 21 },
  dialogSummary: { gap: 8, marginTop: 16 },
  dialogSummaryCard: { marginTop: 16 },
  dialogSummaryContent: { gap: 12 },
  dialogSummaryRow: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  currencyDescription: { alignItems: 'center', flexDirection: 'row', gap: 4 },
  currencyValue: { alignItems: 'center', flexDirection: 'row', gap: 3 },
  facilityCostDetails: { gap: 4 },
  dialogSectionHeading: { marginTop: 16, marginBottom: 4 },
  featureCard: { backgroundColor: colors.surface },
  facilityTopActions: { alignItems: 'center', flexDirection: 'row', gap: 0 },
  facilityHeader: { gap: 5, paddingVertical: 4 },
  facilityHeaderRow: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  facilityMetrics: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  facilityMetric: { alignItems: 'center', backgroundColor: colors.paleGreen, borderRadius: 12, flexDirection: 'row', gap: 3, paddingHorizontal: 7, paddingVertical: 3 },
  facilityMetricText: { color: colors.primary, fontSize: 11, fontWeight: '700' },
  facilityPauseMetric: { alignItems: 'center', backgroundColor: '#FFF1F1', borderRadius: 12, justifyContent: 'center', minHeight: 24, minWidth: 28 },
  facilityRecipeControls: { gap: 6, marginTop: 4 },
  facilityRecipeSelector: { backgroundColor: colors.softBackground, borderRadius: 10, marginTop: 8, overflow: 'hidden' },
  facilityRecipeSelectorHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', paddingLeft: 12 },
  facilityRecipeSelectorTitle: { color: colors.charcoal, fontWeight: '700' },
  facilityRecipeSelectorCurrent: { color: colors.muted, fontSize: 12, paddingHorizontal: 12, paddingBottom: 10 },
  facilityTabList: { backgroundColor: colors.softBackground, borderRadius: 10, flexDirection: 'row', marginTop: 8, padding: 3 },
  facilityTab: { alignItems: 'center', borderRadius: 8, flex: 1, justifyContent: 'center', minHeight: 42, paddingHorizontal: 4 },
  facilityTabActive: { backgroundColor: colors.surface, borderColor: '#D5DEDA', borderWidth: 1 },
  facilityTabLabel: { color: colors.muted, fontSize: 11, fontWeight: '700' },
  facilityTabLabelActive: { color: colors.charcoal },
  facilityRecipeOption: { borderColor: '#D5DEDA', borderRadius: 8, borderWidth: 1, gap: 4, marginHorizontal: 8, marginBottom: 8, padding: 9 },
  facilityRecipeOptionActive: { backgroundColor: '#EAF4FF', borderColor: '#5D9FEA', borderWidth: 2 },
  facilityRecipeOptionUnavailable: { backgroundColor: '#FFF1F1', borderColor: '#D95050' },
  facilityRecipeOptionName: { color: colors.charcoal, fontSize: 13, fontWeight: '700' },
  facilityRecipeOptionDetails: { color: colors.muted, fontSize: 11, lineHeight: 17 },
  facilityRecipeOptionMissing: { color: colors.error },
  facilityRecipeOptionStats: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  facilityRecipeOptionValue: { color: colors.primary, fontSize: 11, fontWeight: '700' },
  facilityProductionTop: { alignItems: 'center', flexDirection: 'row', gap: 4 },
  facilityRecipeActions: { flexDirection: 'row', gap: 2, marginTop: 0 },
  facilityRecipeActionButton: { margin: 0 },
  facilityProductionSection: { backgroundColor: colors.softBackground, borderColor: '#D5DEDA', borderRadius: 10, borderWidth: 1, marginTop: 8, padding: 8 },
  facilityResourceArrow: { color: colors.muted, fontSize: 18, marginHorizontal: 2 },
  facilityResourceEmpty: { color: colors.muted },
  facilityResourceGroup: { flex: 1, gap: 3 },
  facilityResourceItems: { flexDirection: 'row', flexWrap: 'wrap', gap: 5 },
  facilityResourceLabel: { color: colors.muted, fontSize: 10, fontWeight: '700', textTransform: 'uppercase' },
  facilityResourceSummary: { alignItems: 'center', flex: 1, flexDirection: 'row', marginTop: 0 },
  facilityResourceValue: { backgroundColor: '#FFF3D7', borderRadius: 10, color: colors.charcoal, fontSize: 12, fontWeight: '700', paddingHorizontal: 6, paddingVertical: 3 },
  facilityResourceOutput: { alignSelf: 'flex-start', backgroundColor: colors.paleGreen, color: colors.primary },
  facilityStaffingControls: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginTop: 0 },
  facilityStaffingDetail: { color: colors.muted, fontSize: 11 },
  facilityStaffingSummary: { alignItems: 'center', flex: 1 },
  facilityStaffingValue: { color: colors.charcoal, fontWeight: '700' },
  facilityEfficiencySection: { backgroundColor: colors.softBackground, borderColor: '#D5DEDA', borderRadius: 10, borderWidth: 1, gap: 5, marginTop: 8, padding: 8 },
  facilityEfficiencyHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  facilityEfficiencyRow: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  facilityEfficiencyLabel: { color: colors.muted, fontSize: 12 },
  facilityEfficiencyValue: { color: colors.charcoal, fontSize: 12, fontWeight: '700' },
  facilityConditionLabel: { alignItems: 'center', flexDirection: 'row', gap: 4 },
  facilityConditionProgress: { height: 8 },
  facilityEfficiencyControls: { flexDirection: 'row', gap: 8 },
  facilityEfficiencyCard: { backgroundColor: colors.surface, borderColor: '#D5DEDA', borderRadius: 10, borderWidth: 1, flex: 1, gap: 2, padding: 8 },
  facilityConditionSummary: { flex: 1, gap: 4 },
  facilityRepairCost: { color: colors.muted, fontSize: 11 },
  facilityTitle: { color: colors.charcoal, fontWeight: '700' },
  facilityUpgradeControls: { flexDirection: 'row', gap: 8, marginTop: 4 },
  facilityUpgradeCard: { backgroundColor: colors.surface, borderColor: '#D5DEDA', borderRadius: 10, borderWidth: 1, flex: 1, gap: 2, padding: 8 },
  facilityUpgradeHeader: { alignItems: 'center', flexDirection: 'row', gap: 4 },
  facilityUpgradeLabel: { color: colors.charcoal, fontSize: 12, fontWeight: '700' },
  facilityUpgradeAction: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginTop: 2 },
  facilityUpgradeCost: { color: colors.muted, fontSize: 11 },
  facilityUpgradeLevel: { color: colors.primary, fontSize: 12, fontWeight: '700' },
  facilityUpgradeSummary: { color: colors.muted, fontSize: 12, marginTop: 2 },
  facilityUpgradesSection: { backgroundColor: colors.softBackground, borderColor: '#D5DEDA', borderRadius: 10, borderWidth: 1, marginTop: 8, padding: 8 },
  header: { backgroundColor: colors.primary },
  headerActions: { alignItems: 'center', flexDirection: 'row' },
  headerElapsedTime: { alignItems: 'center', flexDirection: 'row', gap: 3, minHeight: 44, paddingHorizontal: 4 },
  headerElapsedTimeValue: { color: colors.onDark, fontSize: 13, fontWeight: '700' },
  inventoryHeading: { color: colors.charcoal, marginTop: 8 },
  marketActionButton: { margin: 0 },
  marketAutomationInput: { marginBottom: 8 },
  marketActions: { alignItems: 'center', flexDirection: 'row', gap: 4, justifyContent: 'flex-end' },
  marketCard: { backgroundColor: colors.surface },
  marketCardContent: { gap: 10 },
  marketInventory: { color: colors.marketGreen, fontSize: 21, fontWeight: '800' },
  marketMetric: { gap: 2 },
  marketMetricColumn: { flex: 1, gap: 10 },
  marketMetricFlowColumn: { flex: 0.85 },
  marketMetricLabel: { color: colors.muted, fontSize: 10, fontWeight: '700', textTransform: 'uppercase' },
  marketMetricValue: { fontSize: 13, fontWeight: '700' },
  marketMetricValueRow: { alignItems: 'center', flexDirection: 'row', gap: 3 },
  marketMetrics: { flexDirection: 'row', gap: 10 },
  marketResourceHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  marketResourceName: { color: colors.charcoal, fontWeight: '700' },
  marketSlider: { marginBottom: 14, minHeight: 62 },
  marketSliderTouchArea: { height: 34, justifyContent: 'center', position: 'relative' },
  marketSliderLabel: { color: colors.muted, fontSize: 11, fontWeight: '700', marginTop: 3 },
  marketSliderLabelActive: { color: colors.primary },
  marketSliderLabels: { flexDirection: 'row', justifyContent: 'space-between' },
  marketSliderStep: { alignItems: 'center', minHeight: 28, minWidth: 36 },
  marketSliderMarker: { backgroundColor: colors.muted, borderRadius: 4, height: 8, width: 8 },
  marketSliderMarkerActive: { backgroundColor: colors.primary, height: 10, width: 10 },
  marketSliderThumb: { backgroundColor: colors.marketAutomationActive, borderRadius: 10, height: 20, marginLeft: -10, position: 'absolute', top: 7, width: 20 },
  marketSliderTrack: { backgroundColor: '#D4DDD9', borderRadius: 3, height: 6, left: 0, position: 'absolute', right: 0, top: 14 },
  marketSliderFill: { backgroundColor: colors.primary, borderRadius: 3, height: 6, left: 0, position: 'absolute', top: 14 },
  inventoryQualityValue: { alignItems: 'center', flexDirection: 'row', gap: 4 },
  navigationItem: {
    alignItems: 'center',
    borderRadius: 12,
    flex: 1,
    gap: 2,
    minHeight: 52,
    justifyContent: 'center',
  },
  navigationLabel: { color: colors.muted, fontSize: 12, fontWeight: '600' },
  navigationSymbol: {
    color: colors.muted,
    fontSize: 20,
    fontWeight: '700',
    lineHeight: 22,
  },
  detailRow: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 62,
    paddingHorizontal: 16,
  },
  detailValue: { color: colors.muted },
  productionError: { color: colors.error, lineHeight: 20, marginTop: 12 },
  productionPercent: { color: colors.muted, fontSize: 12 },
  productionProgress: { gap: 5, marginTop: 8 },
  productionProgressBar: { borderRadius: 6, height: 8 },
  productionProgressHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  productionProgressMeta: { alignItems: 'flex-end', gap: 1 },
  productionTimeLeft: { color: colors.muted, fontSize: 12 },
  productionValue: { color: colors.primary, fontSize: 12, fontWeight: '700' },
  prestigeInline: { alignItems: 'center', flexDirection: 'row', gap: 3, minHeight: 44, paddingHorizontal: 4 },
  prestigeInlineValue: { color: colors.onDark, fontSize: 14, fontWeight: '700' },
  profileButton: { borderRadius: 22, padding: 2 },
  safeArea: { backgroundColor: colors.primary, flex: 1 },
  salesAvailability: { color: colors.muted, fontSize: 12 },
  salesCapacity: { color: colors.primary, fontSize: 13, fontWeight: '700' },
  salesActions: { flexDirection: 'row', gap: 8 },
  salesContractHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', paddingRight: 28 },
  salesRejectButton: { position: 'absolute', right: 2, top: 2 },
  salesFilterButton: { flex: 1 },
  salesFilters: { flexDirection: 'row', gap: 8 },
  salesReward: { color: colors.primary, fontSize: 20, fontWeight: '700' },
  salesResearchGate: { color: colors.error, fontSize: 12, lineHeight: 18 },
  salesResearchReady: { color: colors.primary, fontSize: 12, fontWeight: '700' },
  salesComparison: { color: colors.muted, fontSize: 12 },
  salesComparisonPositive: { color: colors.marketGreen, fontWeight: '700' },
  salesComparisonNegative: { color: colors.error, fontWeight: '700' },
  screen: { backgroundColor: colors.softBackground, flex: 1 },
  sectionEyebrow: {
    color: colors.primary,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.1,
  },
  sectionHeading: { gap: 4, marginBottom: 4 },
  sectionSubtitle: { color: colors.muted, lineHeight: 20 },
  topBar: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 64,
    paddingHorizontal: 20,
  },
  tutorialProductionNavigation: { borderColor: '#FFD54F', borderWidth: 2 },
  tutorialBuildFacilityButton: { borderColor: '#FFD54F', borderWidth: 3 },
  tutorialBuildFacilityCard: { backgroundColor: '#F5EFFB', borderRadius: 24, elevation: 8, marginHorizontal: 32, padding: 24 },
  tutorialBuildFacilityDimmer: { backgroundColor: 'rgba(0, 0, 0, 0.32)', left: 0, position: 'absolute', right: 0 },
  tutorialBalanceSpotlight: { alignItems: 'center', backgroundColor: colors.primary, borderColor: '#FFD54F', borderRadius: 10, borderWidth: 2, flexDirection: 'row', gap: 8, left: 14, paddingHorizontal: 8, paddingVertical: 4, position: 'absolute', top: 10 },
  tutorialActions: { alignItems: 'center', flexDirection: 'row', justifyContent: 'flex-end', marginTop: 16 },
  tutorialDialog: { overflow: 'visible' },
  tutorialDialogTitle: { color: colors.charcoal, fontSize: 24, marginBottom: 18 },
  tutorialGuideCharacterBehind: { height: 110, left: -64, position: 'absolute', top: -70, width: 110, zIndex: -1 },
  tutorialDialogContent: { alignItems: 'center', gap: 12 },
  tutorialProductionCard: { backgroundColor: '#F5EFFB', borderRadius: 24, elevation: 8, marginHorizontal: 32, padding: 24 },
  tutorialProductionDimmerNavigationBottom: { backgroundColor: 'rgba(0, 0, 0, 0.32)', bottom: 0, height: 10, left: 0, position: 'absolute', right: 0 },
  tutorialProductionDimmerNavigationLeft: { backgroundColor: 'rgba(0, 0, 0, 0.32)', bottom: 10, height: 52, left: 0, position: 'absolute', width: '50%' },
  tutorialProductionDimmerNavigationRight: { backgroundColor: 'rgba(0, 0, 0, 0.32)', bottom: 10, height: 52, position: 'absolute', right: 0, width: 12 },
  tutorialProductionDimmerNavigationTop: { backgroundColor: 'rgba(0, 0, 0, 0.32)', bottom: 62, height: 10, left: 0, position: 'absolute', right: 0 },
  tutorialProductionDimmerTop: { backgroundColor: 'rgba(0, 0, 0, 0.32)', bottom: 72, left: 0, position: 'absolute', right: 0, top: 0 },
  tutorialProductionOverlay: { bottom: 0, justifyContent: 'center', left: 0, paddingBottom: 72, position: 'absolute', right: 0, top: 0, zIndex: 10 },
  tutorialReopenButton: { height: 58, width: 58 },
  tutorialReopenCloseButton: { margin: 0, position: 'absolute', right: -6, top: -8 },
  tutorialReopenControl: { bottom: 88, height: 58, position: 'absolute', right: 12, width: 58, zIndex: 20 },
  tutorialReopenCharacter: { height: 68, width: 58 },
  tutorialTimeSpotlight: { alignItems: 'center', backgroundColor: colors.primary, borderColor: '#FFD54F', borderRadius: 10, borderWidth: 2, flexDirection: 'row', gap: 3, paddingHorizontal: 6, paddingVertical: 4, position: 'absolute', right: 50, top: 10 },
  transactionCost: { color: colors.error, fontWeight: '700' },
  transactionDetails: { flex: 1, gap: 2, paddingRight: 12 },
  transactionIcon: { alignItems: 'center', borderRadius: 20, height: 40, justifyContent: 'center', marginRight: 12, width: 40 },
  transactionIconCost: { backgroundColor: '#FBE9E7' },
  transactionIconIncome: { backgroundColor: colors.paleGreen },
  transactionIncome: { color: colors.primary, fontWeight: '700' },
  workMetric: { alignItems: 'center', flexDirection: 'row', gap: 4 },
  workMetricIcon: { color: colors.muted },
});
