import { Image, Pressable, View } from 'react-native';
import { useState } from 'react';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { Button, Dialog, IconButton, Portal, Text } from 'react-native-paper';
import { colors } from '@/theme';
import { getFacilityDefinition, type FacilityType } from '@/game/facilities';
import { ResourceType } from '@/game/resources';
import { styles } from '@/ui/dashboard/helpers/dashboard.styles';
import { formatRecipeName } from '@/ui/dashboard/helpers/recipeFormatters';
import { APP_ICONS } from '@/icons';
import { TooltipMaterialIcon, TooltipResourceIcon } from '@/ui/dashboard/components/IconTooltip';

const SIMULUCIUS_IMAGES = { balance: require('../../../../assets/simulucius/withlaptop.png'), welcome: require('../../../../assets/simulucius/frontremovebg.png') } as const;

function TutorialCollapseControl({ collapsed, onPress }: { collapsed: boolean; onPress: () => void }) {
  return <IconButton accessibilityLabel={collapsed ? 'Expand tutorial' : 'Collapse tutorial'} icon={collapsed ? 'chevron-down' : 'chevron-up'} onPress={onPress} size={20} style={styles.tutorialCollapseControl} />;
}

export function TutorialGuideDialog({ balance, companyOverviewLayout, elapsedTime, onBack, onDismiss, onExit, step, visible, onNext }: { balance: string; companyOverviewLayout: { height: number; width: number; x: number; y: number } | null; elapsedTime: string; onBack: () => void; onDismiss: () => void; onExit: () => void; step: 1 | 2 | 3 | 4 | 5; visible: boolean; onNext: () => void }) {
  const [collapsed, setCollapsed] = useState(false);
  const isBalanceStep = step === 2;
  const isTimeStep = step === 3;
  const isCompanyStep = step === 4;
  const isProductionStep = step === 5;
  const title = isBalanceStep ? 'Your company balance' : isTimeStep ? 'Your company time' : isCompanyStep ? 'Your company overview' : isProductionStep ? 'Production' : 'Welcome to Industri Clicker';
  const description = isProductionStep ? 'Press the Production tab below. I will introduce that view in the next dialog.' : isCompanyStep ? 'This is your company overview. It will become your home base for understanding your company and its progress. I will show you more of this page later.' : isTimeStep ? 'The highlighted value shows your company time. It advances while you play, and helps you follow how long your company has been running and how much progress it has made.' : isBalanceStep ? "The highlighted amount at the top is your company balance. You spend it on construction and upgrades, and earn more by selling resources. Later it will become part of your company's total assets and provide Prestige. I'll tell you more about that later." : "I'll help you get oriented. Start by checking your Company tab. The tutorial stays active while you work through the early game.";
  const guideContent = <View><Image accessibilityLabel="Simulucius, your tutorial guide" resizeMode="contain" source={isBalanceStep ? SIMULUCIUS_IMAGES.balance : SIMULUCIUS_IMAGES.welcome} style={styles.tutorialGuideCharacterBehind} /><Text style={styles.tutorialDialogTitle}>{title}</Text>{!collapsed && <View style={styles.tutorialDialogContent}><Text style={styles.sectionEyebrow}>{`STEP ${step} OF 5`}</Text><Text style={styles.dialogDescription}>{description}</Text></View>}</View>;
  const actions = <View style={styles.tutorialActions}><Button disabled={step === 1} onPress={onBack}>Back</Button><Button onPress={onExit}>Exit tutorial</Button><Button mode="contained" onPress={onNext}>Next</Button></View>;
  const collapseControl = <TutorialCollapseControl collapsed={collapsed} onPress={() => setCollapsed((value) => !value)} />;
  const companySpotlight = companyOverviewLayout ? <><Pressable onPress={onDismiss} style={[styles.tutorialBuildFacilityDimmer, { bottom: undefined, height: companyOverviewLayout.y, top: 0 }]} /><Pressable onPress={onDismiss} style={[styles.tutorialBuildFacilityDimmer, { bottom: 0, top: companyOverviewLayout.y + companyOverviewLayout.height }]} /><Pressable onPress={onDismiss} style={[styles.tutorialBuildFacilityDimmer, { bottom: undefined, height: companyOverviewLayout.height, top: companyOverviewLayout.y, width: companyOverviewLayout.x }]} /><Pressable onPress={onDismiss} style={[styles.tutorialBuildFacilityDimmer, { bottom: undefined, height: companyOverviewLayout.height, left: companyOverviewLayout.x + companyOverviewLayout.width, right: 0, top: companyOverviewLayout.y }]} /></> : <Pressable onPress={onDismiss} style={[styles.tutorialBuildFacilityDimmer, { bottom: 0, top: 0 }]} />;

  return <Portal>{isCompanyStep ? visible && <View pointerEvents="box-none" style={styles.tutorialCompanyOverlay}>{companySpotlight}{companyOverviewLayout && <View pointerEvents="none" style={[styles.tutorialCompanyHighlight, { height: companyOverviewLayout.height, left: companyOverviewLayout.x, top: companyOverviewLayout.y, width: companyOverviewLayout.width }]} />}<View pointerEvents="auto" style={styles.tutorialCompanyCard}>{guideContent}{collapseControl}{actions}</View></View> : isProductionStep ? visible && <View pointerEvents="box-none" style={styles.tutorialProductionOverlay}><Pressable onPress={onDismiss} style={styles.tutorialProductionDimmerTop} /><Pressable onPress={onDismiss} style={styles.tutorialProductionDimmerNavigationTop} /><Pressable onPress={onDismiss} style={styles.tutorialProductionDimmerNavigationBottom} /><Pressable onPress={onDismiss} style={styles.tutorialProductionDimmerNavigationLeft} /><Pressable onPress={onDismiss} style={styles.tutorialProductionDimmerNavigationRight} /><View pointerEvents="auto" style={styles.tutorialProductionCard}>{guideContent}{collapseControl}{actions}</View></View> : <Dialog dismissable onDismiss={onDismiss} style={styles.tutorialDialog} visible={visible}>{guideContent}{collapseControl}<Dialog.Actions>{actions}</Dialog.Actions></Dialog>}{isBalanceStep && visible && <View accessibilityElementsHidden pointerEvents="none" style={styles.tutorialBalanceSpotlight}><MaterialCommunityIcons color={colors.onDark} name="cash" size={21} /><Text style={styles.balanceInlineValue}>{balance}</Text></View>}{isTimeStep && visible && <View accessibilityElementsHidden pointerEvents="none" style={styles.tutorialTimeSpotlight}><MaterialCommunityIcons color={colors.onDark} name="timer-outline" size={17} /><Text style={styles.headerElapsedTimeValue}>{elapsedTime}</Text></View>}</Portal>;
}

export function ProductionTutorialDialog({ visible, onBack, onClose, onDismiss, onExit }: { visible: boolean; onBack: () => void; onClose: () => void; onDismiss: () => void; onExit: () => void }) {
  const [collapsed, setCollapsed] = useState(false);
  return <Portal><Dialog dismissable onDismiss={onDismiss} style={[styles.tutorialDialog, styles.tutorialBottomDialog]} visible={visible}><Image accessibilityLabel="Simulucius, your tutorial guide" resizeMode="contain" source={SIMULUCIUS_IMAGES.welcome} style={styles.tutorialGuideCharacterBehind} /><Dialog.Title>Production</Dialog.Title><TutorialCollapseControl collapsed={collapsed} onPress={() => setCollapsed((value) => !value)} />{!collapsed && <Dialog.Content><View style={styles.tutorialDialogContent}><Text style={styles.sectionEyebrow}>STEP 1 OF 6</Text><Text style={styles.dialogDescription}>This is the Production view. We will explore how your facilities run here next.</Text></View></Dialog.Content>}<Dialog.Actions><Button onPress={onBack}>Back</Button><Button onPress={onExit}>Exit tutorial</Button><Button mode="contained" onPress={onClose}>Next</Button></Dialog.Actions></Dialog></Portal>;
}

export function BuildFacilityTutorialDialog({ highlightLayout, onBack, onDismiss, onExit, onNext, visible }: { highlightLayout: { height: number; width: number; x: number; y: number } | null; onBack: () => void; onDismiss: () => void; onExit: () => void; onNext: () => void; visible: boolean }) {
  const [collapsed, setCollapsed] = useState(false);
  const dimmer = styles.tutorialBuildFacilityDimmer;
  return <Portal>{visible && <View pointerEvents="box-none" style={styles.tutorialProductionOverlay}>{highlightLayout ? <><Pressable onPress={onDismiss} style={[dimmer, { bottom: undefined, height: highlightLayout.y, top: 0 }]} /><Pressable onPress={onDismiss} style={[dimmer, { bottom: 0, top: highlightLayout.y + highlightLayout.height }]} /><Pressable onPress={onDismiss} style={[dimmer, { bottom: undefined, height: highlightLayout.height, top: highlightLayout.y, width: highlightLayout.x }]} /><Pressable onPress={onDismiss} style={[dimmer, { bottom: undefined, height: highlightLayout.height, left: highlightLayout.x + highlightLayout.width, right: 0, top: highlightLayout.y }]} /></> : <Pressable onPress={onDismiss} style={[dimmer, { bottom: 0, top: 0 }]} />}<View pointerEvents="auto" style={styles.tutorialBuildFacilityCard}><Image accessibilityLabel="Simulucius, your tutorial guide" resizeMode="contain" source={SIMULUCIUS_IMAGES.welcome} style={styles.tutorialGuideCharacterBehind} /><Text style={styles.tutorialDialogTitle}>Build a facility</Text><TutorialCollapseControl collapsed={collapsed} onPress={() => setCollapsed((value) => !value)} />{!collapsed && <View style={styles.tutorialDialogContent}><Text style={styles.sectionEyebrow}>STEP 2 OF 6</Text><Text style={styles.dialogDescription}>Press “Build facility” to construct your first facility.</Text></View>}<View style={styles.tutorialActions}><Button onPress={onBack}>Back</Button><Button onPress={onExit}>Exit tutorial</Button><Button mode="contained" onPress={onNext}>Next</Button></View></View></View>}</Portal>;
}

export function ConstructionTutorialDialog({ onBack, onExit, onNext, visible }: { onBack: () => void; onExit: () => void; onNext: () => void; visible: boolean }) {
  const [collapsed, setCollapsed] = useState(false);
  return <Portal>{visible && <View pointerEvents="box-none" style={styles.tutorialProductionOverlay}><View pointerEvents="auto" style={styles.tutorialFacilityChoiceCard}><Image accessibilityLabel="Simulucius, your tutorial guide" resizeMode="contain" source={SIMULUCIUS_IMAGES.welcome} style={styles.tutorialGuideCharacterBehind} /><Text style={styles.tutorialDialogTitle}>Choose your first facility</Text><TutorialCollapseControl collapsed={collapsed} onPress={() => setCollapsed((value) => !value)} />{!collapsed && <View style={styles.tutorialFacilityChoiceContent}><Text style={styles.sectionEyebrow}>STEP 3 OF 6</Text><Text style={styles.dialogDescription}>You can choose between three affordable starting facilities. Each choice opens a different production path.</Text><Text style={styles.dialogDescription}>Use the filter to show all facilities, only those you can build now, or unavailable choices.</Text><Text style={styles.dialogDescription}>Scroll through the list to see the facilities available to you. You can tap a facility now or continue to the comparison step.</Text></View>}<View style={[styles.tutorialActions, styles.tutorialFacilityChoiceActions]}><Button onPress={onBack}>Back</Button><Button onPress={onExit}>Exit tutorial</Button><Button mode="contained" onPress={onNext}>Next</Button></View></View></View>}</Portal>;
}

export function FacilityChoiceTutorialDialog({ onBack, onExit, onNext, visible }: { onBack: () => void; onExit: () => void; onNext: () => void; visible: boolean }) {
  const [collapsed, setCollapsed] = useState(false);
  return <Portal>{visible && <View pointerEvents="box-none" style={styles.tutorialProductionOverlay}><View pointerEvents="auto" style={styles.tutorialFacilityChoiceCard}><Image accessibilityLabel="Simulucius, your tutorial guide" resizeMode="contain" source={SIMULUCIUS_IMAGES.welcome} style={styles.tutorialGuideCharacterBehind} /><Text style={styles.tutorialDialogTitle}>Comparing facilities</Text><TutorialCollapseControl collapsed={collapsed} onPress={() => setCollapsed((value) => !value)} />{!collapsed && <View style={styles.tutorialFacilityChoiceContent}><Text style={styles.sectionEyebrow}>STEP 4 OF 6</Text><Text style={styles.dialogDescription}>Every facility has three costs: <TooltipMaterialIcon color={colors.primary} label="Land cost" name={APP_ICONS.coin} size={15} /> Land, <TooltipResourceIcon resourceType={ResourceType.ConstructionMaterials} /> Construction Materials, and <TooltipResourceIcon resourceType={ResourceType.IndustrialMachines} /> Industrial Machines.</Text><Text style={styles.dialogDescription}>Construction Materials and Industrial Machines prices are per unit. Market replacement cost is the combined current value of all three.</Text><Text style={styles.dialogDescription}>Tap a facility to review its construction details, or press Next to continue without selecting one.</Text></View>}<View style={[styles.tutorialActions, styles.tutorialFacilityChoiceActions]}><Button onPress={onBack}>Back</Button><Button onPress={onExit}>Exit tutorial</Button><Button mode="contained" onPress={onNext}>Next</Button></View></View></View>}</Portal>;
}

export function ConstructionConfirmationTutorialDialog({ onBack, onExit, onNext, visible }: { onBack: () => void; onExit: () => void; onNext: () => void; visible: boolean }) {
  const [collapsed, setCollapsed] = useState(false);
  if (!visible) return null;
  return <Portal><View pointerEvents="box-none" style={styles.tutorialProductionOverlay}><View pointerEvents="auto" style={styles.tutorialFacilityChoiceCard}><Image accessibilityLabel="Simulucius, your tutorial guide" resizeMode="contain" source={SIMULUCIUS_IMAGES.welcome} style={styles.tutorialGuideCharacterBehind} /><Text style={styles.tutorialDialogTitle}>Confirm construction</Text><TutorialCollapseControl collapsed={collapsed} onPress={() => setCollapsed((value) => !value)} />{!collapsed && <View style={styles.tutorialFacilityChoiceContent}><Text style={styles.sectionEyebrow}>STEP 5 OF 6</Text><Text style={styles.dialogDescription}>Review the land purchase and the Construction Materials and Industrial Machines taken from your inventory.</Text><Text style={styles.dialogDescription}>If inputs are missing, Buy missing inputs can purchase them at current market prices.</Text><Text style={styles.dialogDescription}>Recipes start collapsed to keep the dialog compact. Tap a recipe to see its inputs, outputs, and required work.</Text></View>}<View style={[styles.tutorialActions, styles.tutorialFacilityChoiceActions]}><Button onPress={onBack}>Back</Button><Button onPress={onExit}>Exit tutorial</Button><Button mode="contained" onPress={onNext}>Next</Button></View></View></View></Portal>;
}

export function FirstFacilityTutorialDialog({ facilityType, onBack, onDismiss, onExit, onNext, visible }: { facilityType: FacilityType | null; onBack: () => void; onDismiss: () => void; onExit: () => void; onNext: () => void; visible: boolean }) {
  const [collapsed, setCollapsed] = useState(false);
  if (!facilityType) return null;
  const definition = getFacilityDefinition(facilityType);
  const recipe = definition.recipes[0];
  const resourceMessage = recipe.inputs.length === 0 ? `${formatRecipeName(recipe)} has no inputs, so it can begin producing immediately.` : `The "Industrial Footprint 1" achievement gave you 10 Water and 10 Electricity. That is enough to run the recipe: "${formatRecipeName(recipe)}" for a little while.`;
  return <Portal>{visible && <View pointerEvents="box-none" style={styles.tutorialFirstFacilityOverlay}><View pointerEvents="auto" style={styles.tutorialFirstFacilityOverlayCard}><Image accessibilityLabel="Simulucius, your tutorial guide" resizeMode="contain" source={SIMULUCIUS_IMAGES.welcome} style={styles.tutorialGuideCharacterBehind} /><Text style={styles.tutorialDialogTitle}>Your first facility</Text><TutorialCollapseControl collapsed={collapsed} onPress={() => setCollapsed((value) => !value)} />{!collapsed && <View style={styles.tutorialDialogContent}><Text style={styles.sectionEyebrow}>STEP 6 OF 6</Text><Text style={styles.dialogDescription}>{`This is your first facility: a ${definition.name}.`}</Text><Text style={styles.dialogDescription}>{resourceMessage}</Text><Text style={styles.dialogDescription}>Scroll through the facility dashboard to see its recipe, staffing, repairs, and upgrades.</Text></View>}<View style={styles.tutorialActions}><Button onPress={onBack}>Back</Button><Button onPress={onExit}>Exit tutorial</Button><Button mode="contained" onPress={onNext}>Finish</Button></View></View></View>}</Portal>;
}
