import { Image, Pressable, View } from 'react-native';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { Button, Dialog, Portal, Text } from 'react-native-paper';
import { colors } from '@/theme';
import { getFacilityDefinition, type FacilityType } from '@/game/facilities';
import { styles } from '@/ui/dashboard/helpers/dashboard.styles';
import { formatRecipeName } from '@/ui/dashboard/helpers/recipeFormatters';

const SIMULUCIUS_IMAGES = { balance: require('../../../../assets/simulucius/withlaptop.png'), welcome: require('../../../../assets/simulucius/frontremovebg.png') } as const;

export function TutorialGuideDialog({ balance, elapsedTime, onBack, onDismiss, onExit, step, visible, onNext }: { balance: string; elapsedTime: string; onBack: () => void; onDismiss: () => void; onExit: () => void; step: 1 | 2 | 3 | 4 | 5; visible: boolean; onNext: () => void }) {
  const isBalanceStep = step === 2; const isTimeStep = step === 3; const isCompanyStep = step === 4; const isProductionStep = step === 5;
  const title = isBalanceStep ? 'Your company balance' : isTimeStep ? 'Your company time' : isCompanyStep ? 'Your company overview' : isProductionStep ? 'Production' : 'Welcome to Industri Clicker';
  const description = isProductionStep ? 'Press the Production tab below. I will introduce that view in the next dialog.' : isCompanyStep ? 'This is your company overview. It will become your home base for understanding your company and its progress. I will show you more of this page later.' : isTimeStep ? 'The highlighted value shows your company time. It advances while you play, and helps you follow how long your company has been running and how much progress it has made.' : isBalanceStep ? "The highlighted amount at the top is your company balance. You spend it on construction and upgrades, and earn more by selling resources. Later it will become part of your company's total assets and provide Prestige. I'll tell you more about that later." : "I'll help you get oriented. Start by checking your Company tab. The tutorial stays active while you work through the early game.";
  const guideContent = <View><Image accessibilityLabel="Simulucius, your tutorial guide" resizeMode="contain" source={isBalanceStep ? SIMULUCIUS_IMAGES.balance : SIMULUCIUS_IMAGES.welcome} style={styles.tutorialGuideCharacterBehind} /><Text style={styles.tutorialDialogTitle}>{title}</Text><View style={styles.tutorialDialogContent}><Text style={styles.sectionEyebrow}>{`STEP ${step} OF 5`}</Text><Text style={styles.dialogDescription}>{description}</Text></View></View>;
  const actions = <View style={styles.tutorialActions}><Button disabled={step === 1} onPress={onBack}>Back</Button><Button onPress={onExit}>Exit tutorial</Button><Button mode="contained" onPress={onNext}>Next</Button></View>;
  return <Portal>{isProductionStep ? visible && <View pointerEvents="box-none" style={styles.tutorialProductionOverlay}><Pressable onPress={onDismiss} style={styles.tutorialProductionDimmerTop} /><Pressable onPress={onDismiss} style={styles.tutorialProductionDimmerNavigationTop} /><Pressable onPress={onDismiss} style={styles.tutorialProductionDimmerNavigationBottom} /><Pressable onPress={onDismiss} style={styles.tutorialProductionDimmerNavigationLeft} /><Pressable onPress={onDismiss} style={styles.tutorialProductionDimmerNavigationRight} /><View pointerEvents="auto" style={styles.tutorialProductionCard}>{guideContent}{actions}</View></View> : <Dialog dismissable onDismiss={onDismiss} style={styles.tutorialDialog} visible={visible}>{guideContent}<Dialog.Actions>{actions}</Dialog.Actions></Dialog>}{isBalanceStep && visible && <View accessibilityElementsHidden pointerEvents="none" style={styles.tutorialBalanceSpotlight}><MaterialCommunityIcons color={colors.onDark} name="cash" size={21} /><Text style={styles.balanceInlineValue}>{balance}</Text></View>}{isTimeStep && visible && <View accessibilityElementsHidden pointerEvents="none" style={styles.tutorialTimeSpotlight}><MaterialCommunityIcons color={colors.onDark} name="timer-outline" size={17} /><Text style={styles.headerElapsedTimeValue}>{elapsedTime}</Text></View>}</Portal>;
}

export function ProductionTutorialDialog({ visible, onBack, onClose, onDismiss, onExit }: { visible: boolean; onBack: () => void; onClose: () => void; onDismiss: () => void; onExit: () => void }) { return <Portal><Dialog dismissable onDismiss={onDismiss} style={styles.tutorialDialog} visible={visible}><Image accessibilityLabel="Simulucius, your tutorial guide" resizeMode="contain" source={SIMULUCIUS_IMAGES.welcome} style={styles.tutorialGuideCharacterBehind} /><Dialog.Title>Production</Dialog.Title><Dialog.Content><View style={styles.tutorialDialogContent}><Text style={styles.sectionEyebrow}>STEP 1 OF 4</Text><Text style={styles.dialogDescription}>This is the Production view. We will explore how your facilities run here next.</Text></View></Dialog.Content><Dialog.Actions><Button onPress={onBack}>Back</Button><Button onPress={onExit}>Exit tutorial</Button><Button mode="contained" onPress={onClose}>Next</Button></Dialog.Actions></Dialog></Portal>; }

export function BuildFacilityTutorialDialog({ highlightLayout, onBack, onDismiss, onExit, onNext, visible }: { highlightLayout: { height: number; width: number; x: number; y: number } | null; onBack: () => void; onDismiss: () => void; onExit: () => void; onNext: () => void; visible: boolean }) {
  const dimmer = styles.tutorialBuildFacilityDimmer;
  return <Portal>{visible && <View pointerEvents="box-none" style={styles.tutorialProductionOverlay}>{highlightLayout ? <><Pressable onPress={onDismiss} style={[dimmer, { bottom: undefined, height: highlightLayout.y, top: 0 }]} /><Pressable onPress={onDismiss} style={[dimmer, { bottom: 0, top: highlightLayout.y + highlightLayout.height }]} /><Pressable onPress={onDismiss} style={[dimmer, { bottom: undefined, height: highlightLayout.height, top: highlightLayout.y, width: highlightLayout.x }]} /><Pressable onPress={onDismiss} style={[dimmer, { bottom: undefined, height: highlightLayout.height, left: highlightLayout.x + highlightLayout.width, right: 0, top: highlightLayout.y }]} /></> : <Pressable onPress={onDismiss} style={[dimmer, { bottom: 0, top: 0 }]} />}<View pointerEvents="auto" style={styles.tutorialBuildFacilityCard}><Image accessibilityLabel="Simulucius, your tutorial guide" resizeMode="contain" source={SIMULUCIUS_IMAGES.welcome} style={styles.tutorialGuideCharacterBehind} /><Text style={styles.tutorialDialogTitle}>Build a facility</Text><View style={styles.tutorialDialogContent}><Text style={styles.sectionEyebrow}>STEP 2 OF 4</Text><Text style={styles.dialogDescription}>Press “Build facility” to construct your first facility.</Text></View><View style={styles.tutorialActions}><Button onPress={onBack}>Back</Button><Button onPress={onExit}>Exit tutorial</Button><Button mode="contained" onPress={onNext}>Next</Button></View></View></View>}</Portal>;
}

export function ConstructionTutorialDialog({ onBack, onDismiss, onExit, onNext, visible }: { onBack: () => void; onDismiss: () => void; onExit: () => void; onNext: () => void; visible: boolean }) { return <Portal><Dialog dismissable onDismiss={onDismiss} style={styles.tutorialDialog} visible={visible}><Image accessibilityLabel="Simulucius, your tutorial guide" resizeMode="contain" source={SIMULUCIUS_IMAGES.welcome} style={styles.tutorialGuideCharacterBehind} /><Dialog.Title>Choose your first facility</Dialog.Title><Dialog.Content><View style={styles.tutorialDialogContent}><Text style={styles.sectionEyebrow}>STEP 3 OF 4</Text><Text style={styles.dialogDescription}>You can choose between three affordable starting facilities. Each choice opens a different production path.</Text><Text style={styles.dialogDescription}>Every facility costs a combination of land paid in euros and Construction Materials.</Text></View></Dialog.Content><Dialog.Actions><Button onPress={onBack}>Back</Button><Button onPress={onExit}>Exit tutorial</Button><Button mode="contained" onPress={onNext}>Choose facility</Button></Dialog.Actions></Dialog></Portal>; }

export function FirstFacilityTutorialDialog({ facilityType, onBack, onDismiss, onExit, onNext, visible }: { facilityType: FacilityType | null; onBack: () => void; onDismiss: () => void; onExit: () => void; onNext: () => void; visible: boolean }) {
  if (!facilityType) return null;
  const definition = getFacilityDefinition(facilityType); const recipe = definition.recipes[0];
  const resourceMessage = recipe.inputs.length === 0 ? `${formatRecipeName(recipe)} has no inputs, so it can begin producing immediately.` : `The "Industrial Footprint 1" achievement gave you 10 Water and 10 Electricity. That is enough to run the recipe: "${formatRecipeName(recipe)}" for a little while.`;
  return <Portal><Dialog dismissable onDismiss={onDismiss} style={styles.tutorialDialog} visible={visible}><Image accessibilityLabel="Simulucius, your tutorial guide" resizeMode="contain" source={SIMULUCIUS_IMAGES.welcome} style={styles.tutorialGuideCharacterBehind} /><Dialog.Title>Your first facility</Dialog.Title><Dialog.Content><View style={styles.tutorialDialogContent}><Text style={styles.sectionEyebrow}>STEP 4 OF 4</Text><Text style={styles.dialogDescription}>{`This is your first facility: a ${definition.name}.`}</Text><Text style={styles.dialogDescription}>{resourceMessage}</Text></View></Dialog.Content><Dialog.Actions><Button onPress={onBack}>Back</Button><Button onPress={onExit}>Exit tutorial</Button><Button mode="contained" onPress={onNext}>Finish</Button></Dialog.Actions></Dialog></Portal>;
}
