import { StyleSheet } from 'react-native';

import { colors } from '@/theme';

export const styles = StyleSheet.create({
  activeNavigationItem: { backgroundColor: colors.paleGreen },
  activeNavigationText: { color: colors.primary, fontWeight: '700' },
  avatar: { backgroundColor: '#D9EDE5' },
  balanceInline: { alignItems: 'center', flexDirection: 'row', gap: 8 },
  balanceInlineValue: { color: colors.onDark, fontSize: 20, fontWeight: '700' },
  balanceValue: { color: colors.charcoal, fontSize: 36, fontWeight: '700', lineHeight: 42 },
  coinIcon: { fontSize: 21 },
  bottomNavigation: {
    backgroundColor: colors.surface,
    flexDirection: 'row',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  cardContent: { gap: 8 },
  cardDescription: { color: colors.muted, lineHeight: 21 },
  cardKicker: {
    color: colors.primary,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1,
  },
  content: { gap: 12, padding: 20, paddingBottom: 28 },
  constructionYardCard: { backgroundColor: colors.softBackground },
  constructionYardDialog: { maxHeight: '88%' },
  constructionYardDialogContent: { flexShrink: 1 },
  constructionYardFunds: { color: colors.primary, fontWeight: '700', marginTop: 12 },
  constructionYardList: { gap: 12, paddingVertical: 16 },
  constructionYardListViewport: { flexShrink: 1 },
  constructionYardRecipe: { color: colors.muted, lineHeight: 20, marginTop: 4 },
  constructionYardRecipeLabel: { color: colors.charcoal, fontWeight: '700', marginTop: 8 },
  dialogDescription: { color: colors.muted, lineHeight: 21 },
  dialogSummary: { gap: 8, marginTop: 16 },
  dialogSectionHeading: { marginTop: 16, marginBottom: 4 },
  featureCard: { backgroundColor: colors.surface },
  facilityActions: { alignItems: 'flex-end', marginTop: 4 },
  facilityRecipeControls: { gap: 8, marginTop: 8 },
  facilityTitle: { color: colors.charcoal, fontWeight: '700' },
  header: { backgroundColor: colors.primary },
  headerActions: { alignItems: 'center', flexDirection: 'row' },
  inventoryHeading: { color: colors.charcoal, marginTop: 8 },
  largePlaceholder: {
    color: colors.charcoal,
    fontSize: 40,
    fontWeight: '700',
    lineHeight: 45,
  },
  navigationItem: {
    alignItems: 'center',
    borderRadius: 12,
    flex: 1,
    gap: 2,
    minHeight: 52,
    justifyContent: 'center',
  },
  navigationLabel: { color: colors.muted, fontSize: 12, fontWeight: '600' },
  navigationSymbol: {
    color: colors.muted,
    fontSize: 20,
    fontWeight: '700',
    lineHeight: 22,
  },
  placeholderRow: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 62,
    paddingHorizontal: 16,
  },
  placeholderValue: { color: colors.muted },
  productionError: { color: colors.error, lineHeight: 20, marginTop: 12 },
  productionPercent: { color: colors.muted, fontSize: 12 },
  productionProgress: { gap: 6, marginTop: 12 },
  productionProgressBar: { borderRadius: 6, height: 8 },
  productionProgressHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  productionTimeLeft: { alignSelf: 'flex-end', color: colors.muted, fontSize: 12, marginBottom: 8 },
  productionValuePlaceholder: { color: colors.primary, fontSize: 12, fontWeight: '700' },
  profileButton: { borderRadius: 22, padding: 2 },
  safeArea: { backgroundColor: colors.primary, flex: 1 },
  screen: { backgroundColor: colors.softBackground, flex: 1 },
  sectionEyebrow: {
    color: colors.primary,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.1,
  },
  sectionHeading: { gap: 4, marginBottom: 4 },
  sectionSubtitle: { color: colors.muted, lineHeight: 20 },
  topBar: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 64,
    paddingHorizontal: 20,
  },
  transactionCost: { color: colors.error, fontWeight: '700' },
  transactionDetails: { flex: 1, gap: 2, paddingRight: 12 },
  transactionIncome: { color: colors.primary, fontWeight: '700' },
});
