import { ResourceType } from '../resources/resourceTypes';
import { Recipe, RecipeName } from './recipeTypes';

export const ALL_RECIPES: Readonly<Record<RecipeName, Recipe>> = {
  [RecipeName.GrowGrain]: {
    name: RecipeName.GrowGrain,
    inputs: [
      { resourceType: ResourceType.Water, amount: 1 },
      { resourceType: ResourceType.Electricity, amount: 1 },
      { resourceType: ResourceType.Fertilizer, amount: 0.025 },
    ],
    outputs: [{ resourceType: ResourceType.Grain, amount: 1.2 }],
    requiredWork: 0.06,
    conditionWearMultiplier: 0.75,
  },
  [RecipeName.BakeBread]: {
    name: RecipeName.BakeBread,
    inputs: [
      { resourceType: ResourceType.Grain, amount: 1.5 },
      { resourceType: ResourceType.Water, amount: 1 },
      { resourceType: ResourceType.Electricity, amount: 1 },
    ],
    outputs: [{ resourceType: ResourceType.Bread, amount: 4.5 }],
    requiredWork: 0.26,
    conditionWearMultiplier: 0.9,
  },
  [RecipeName.ProduceWater]: {
    name: RecipeName.ProduceWater,
    inputs: [],
    outputs: [{ resourceType: ResourceType.Water, amount: 2 }],
    requiredWork: 0.073,
    conditionWearMultiplier: 0.5,
  },
  [RecipeName.ProduceElectricity]: {
    name: RecipeName.ProduceElectricity,
    inputs: [],
    outputs: [{ resourceType: ResourceType.Electricity, amount: 2 }],
    requiredWork: 0.11,
    conditionWearMultiplier: 0.8,
  },
  [RecipeName.GrowSugar]: {
    name: RecipeName.GrowSugar,
    inputs: [
      { resourceType: ResourceType.Water, amount: 3 },
      { resourceType: ResourceType.Fertilizer, amount: 0.04 },
    ],
    outputs: [{ resourceType: ResourceType.Sugar, amount: 1.2 }],
    requiredWork: 0.12,
    conditionWearMultiplier: 0.8,
  },
  [RecipeName.GrowFruit]: {
    name: RecipeName.GrowFruit,
    inputs: [
      { resourceType: ResourceType.Water, amount: 2 },
      { resourceType: ResourceType.Fertilizer, amount: 0.03 },
    ],
    outputs: [{ resourceType: ResourceType.Fruit, amount: 2 }],
    requiredWork: 0.16,
    conditionWearMultiplier: 0.8,
  },
  [RecipeName.RaiseCattle]: {
    name: RecipeName.RaiseCattle,
    inputs: [
      { resourceType: ResourceType.Grain, amount: 12 },
      { resourceType: ResourceType.Water, amount: 8 },
      { resourceType: ResourceType.Electricity, amount: 5 },
    ],
    outputs: [
      { resourceType: ResourceType.Meat, amount: 2 },
      { resourceType: ResourceType.Milk, amount: 5 },
      { resourceType: ResourceType.Fertilizer, amount: 0.2 },
    ],
    requiredWork: 2.45,
    conditionWearMultiplier: 1.4,
  },
  [RecipeName.RaiseSheep]: {
    name: RecipeName.RaiseSheep,
    inputs: [
      { resourceType: ResourceType.Grain, amount: 8 },
      { resourceType: ResourceType.Water, amount: 6 },
      { resourceType: ResourceType.Electricity, amount: 4 },
    ],
    outputs: [
      { resourceType: ResourceType.Meat, amount: 1.5 },
      { resourceType: ResourceType.Wool, amount: 2 },
      { resourceType: ResourceType.Fertilizer, amount: 0.1 },
    ],
    requiredWork: 1.75,
    conditionWearMultiplier: 1.2,
  },
  [RecipeName.RaiseChicken]: {
    name: RecipeName.RaiseChicken,
    inputs: [
      { resourceType: ResourceType.Grain, amount: 4 },
      { resourceType: ResourceType.Water, amount: 4 },
      { resourceType: ResourceType.Electricity, amount: 3 },
    ],
    outputs: [
      { resourceType: ResourceType.Meat, amount: 1 },
      { resourceType: ResourceType.Eggs, amount: 5 },
      { resourceType: ResourceType.Fertilizer, amount: 0.05 },
    ],
    requiredWork: 1.4,
    conditionWearMultiplier: 1,
  },
  [RecipeName.MineIron]: {
    name: RecipeName.MineIron,
    inputs: [
      { resourceType: ResourceType.Water, amount: 2 },
      { resourceType: ResourceType.Electricity, amount: 4 },
      { resourceType: ResourceType.Chemicals, amount: 0.1 },
    ],
    outputs: [{ resourceType: ResourceType.Iron, amount: 1.25 }],
    requiredWork: 0.267,
    conditionWearMultiplier: 1.1,
  },
  [RecipeName.MineCoal]: {
    name: RecipeName.MineCoal,
    inputs: [
      { resourceType: ResourceType.Water, amount: 1 },
      { resourceType: ResourceType.Electricity, amount: 2 },
    ],
    outputs: [{ resourceType: ResourceType.Coal, amount: 2.5 }],
    requiredWork: 0.2,
    conditionWearMultiplier: 1,
  },
  [RecipeName.MineCopper]: {
    name: RecipeName.MineCopper,
    inputs: [
      { resourceType: ResourceType.Water, amount: 2 },
      { resourceType: ResourceType.Electricity, amount: 5 },
      { resourceType: ResourceType.Chemicals, amount: 0.1 },
    ],
    outputs: [{ resourceType: ResourceType.Copper, amount: 1.25 }],
    requiredWork: 0.333,
    conditionWearMultiplier: 1.2,
  },
  [RecipeName.QuarrySand]: {
    name: RecipeName.QuarrySand,
    inputs: [
      { resourceType: ResourceType.Water, amount: 1 },
      { resourceType: ResourceType.Electricity, amount: 1 },
    ],
    outputs: [{ resourceType: ResourceType.Sand, amount: 3 }],
    requiredWork: 0.107,
    conditionWearMultiplier: 0.6,
  },
  [RecipeName.QuarryClay]: {
    name: RecipeName.QuarryClay,
    inputs: [
      { resourceType: ResourceType.Water, amount: 2 },
      { resourceType: ResourceType.Electricity, amount: 1 },
    ],
    outputs: [{ resourceType: ResourceType.Clay, amount: 2 }],
    requiredWork: 0.16,
    conditionWearMultiplier: 0.7,
  },
  [RecipeName.QuarryStone]: {
    name: RecipeName.QuarryStone,
    inputs: [
      { resourceType: ResourceType.Water, amount: 1 },
      { resourceType: ResourceType.Electricity, amount: 4 },
    ],
    outputs: [{ resourceType: ResourceType.Stone, amount: 3 }],
    requiredWork: 0.213,
    conditionWearMultiplier: 0.8,
  },
  [RecipeName.QuarryMinerals]: {
    name: RecipeName.QuarryMinerals,
    inputs: [
      { resourceType: ResourceType.Water, amount: 1 },
      { resourceType: ResourceType.Electricity, amount: 2 },
    ],
    outputs: [{ resourceType: ResourceType.Minerals, amount: 3 }],
    requiredWork: 0.16,
    conditionWearMultiplier: 0.7,
  },
  [RecipeName.MineGold]: {
    name: RecipeName.MineGold,
    inputs: [
      { resourceType: ResourceType.Water, amount: 3 },
      { resourceType: ResourceType.Electricity, amount: 8 },
    ],
    outputs: [{ resourceType: ResourceType.Gold, amount: 0.2 }],
    requiredWork: 0.667,
    conditionWearMultiplier: 1.4,
  },
  [RecipeName.ProduceSteel]: {
    name: RecipeName.ProduceSteel,
    inputs: [
      { resourceType: ResourceType.Iron, amount: 2 },
      { resourceType: ResourceType.Coal, amount: 1 },
      { resourceType: ResourceType.Water, amount: 2 },
      { resourceType: ResourceType.Electricity, amount: 6 },
    ],
    outputs: [{ resourceType: ResourceType.Steel, amount: 6 }],
    requiredWork: 1.1,
    conditionWearMultiplier: 1.2,
  },
  [RecipeName.ProduceElectricCircuits]: {
    name: RecipeName.ProduceElectricCircuits,
    inputs: [
      { resourceType: ResourceType.Copper, amount: 2 },
      { resourceType: ResourceType.Silicon, amount: 1 },
      { resourceType: ResourceType.Plastic, amount: 1 },
      { resourceType: ResourceType.Water, amount: 1 },
      { resourceType: ResourceType.Electricity, amount: 4 },
    ],
    outputs: [{ resourceType: ResourceType.ElectricCircuits, amount: 5 }],
    requiredWork: 1.65,
    conditionWearMultiplier: 1.4,
  },
  [RecipeName.ProduceChemicals]: {
    name: RecipeName.ProduceChemicals,
    inputs: [
      { resourceType: ResourceType.Minerals, amount: 2 },
      { resourceType: ResourceType.Water, amount: 2 },
      { resourceType: ResourceType.Electricity, amount: 4 },
    ],
    outputs: [{ resourceType: ResourceType.Chemicals, amount: 4 }],
    requiredWork: 2.5,
    conditionWearMultiplier: 1.4,
  },
  [RecipeName.SynthesizeFertilizer]: {
    name: RecipeName.SynthesizeFertilizer,
    inputs: [
      { resourceType: ResourceType.Chemicals, amount: 1 },
      { resourceType: ResourceType.Minerals, amount: 1 },
      { resourceType: ResourceType.Water, amount: 1 },
      { resourceType: ResourceType.Electricity, amount: 2 },
    ],
    outputs: [{ resourceType: ResourceType.Fertilizer, amount: 4 }],
    requiredWork: 1.667,
    conditionWearMultiplier: 1.3,
  },
  [RecipeName.ProducePlastic]: {
    name: RecipeName.ProducePlastic,
    inputs: [
      { resourceType: ResourceType.Chemicals, amount: 2 },
      { resourceType: ResourceType.Water, amount: 1 },
      { resourceType: ResourceType.Electricity, amount: 3 },
    ],
    outputs: [{ resourceType: ResourceType.Plastic, amount: 4 }],
    requiredWork: 1.667,
    conditionWearMultiplier: 1.2,
  },
  [RecipeName.ProduceSilicon]: {
    name: RecipeName.ProduceSilicon,
    inputs: [
      { resourceType: ResourceType.Minerals, amount: 3 },
      { resourceType: ResourceType.Sand, amount: 3 },
      { resourceType: ResourceType.Electricity, amount: 5 },
    ],
    outputs: [{ resourceType: ResourceType.Silicon, amount: 2 }],
    requiredWork: 2.017,
    conditionWearMultiplier: 1.3,
  },
  [RecipeName.ProduceAdvancedComponents]: {
    name: RecipeName.ProduceAdvancedComponents,
    inputs: [
      { resourceType: ResourceType.ElectricCircuits, amount: 2 },
      { resourceType: ResourceType.Silicon, amount: 2 },
      { resourceType: ResourceType.Gold, amount: 0.1 },
      { resourceType: ResourceType.Water, amount: 1 },
      { resourceType: ResourceType.Electricity, amount: 4 },
    ],
    outputs: [{ resourceType: ResourceType.AdvancedComponents, amount: 3 }],
    requiredWork: 3.025,
    conditionWearMultiplier: 1.5,
  },
  [RecipeName.AssembleIndustrialMachines]: {
    name: RecipeName.AssembleIndustrialMachines,
    inputs: [
      { resourceType: ResourceType.Steel, amount: 6 },
      { resourceType: ResourceType.ElectricCircuits, amount: 3 },
      { resourceType: ResourceType.AdvancedComponents, amount: 2 },
      { resourceType: ResourceType.Water, amount: 2 },
      { resourceType: ResourceType.Electricity, amount: 6 },
    ],
    outputs: [{ resourceType: ResourceType.IndustrialMachines, amount: 4 }],
    requiredWork: 5.95,
    conditionWearMultiplier: 1.7,
  },
  [RecipeName.ProduceBricks]: {
    name: RecipeName.ProduceBricks,
    inputs: [
      { resourceType: ResourceType.Clay, amount: 2 },
      { resourceType: ResourceType.Sand, amount: 1 },
      { resourceType: ResourceType.Water, amount: 1 },
      { resourceType: ResourceType.Electricity, amount: 3 },
    ],
    outputs: [{ resourceType: ResourceType.Bricks, amount: 12 }],
    requiredWork: 0.65,
    conditionWearMultiplier: 0.75,
  },
  [RecipeName.ProduceCement]: {
    name: RecipeName.ProduceCement,
    inputs: [
      { resourceType: ResourceType.Stone, amount: 3 },
      { resourceType: ResourceType.Clay, amount: 1 },
      { resourceType: ResourceType.Minerals, amount: 1 },
      { resourceType: ResourceType.Water, amount: 1 },
      { resourceType: ResourceType.Electricity, amount: 5 },
    ],
    outputs: [{ resourceType: ResourceType.Cement, amount: 7 }],
    requiredWork: 1.083,
    conditionWearMultiplier: 1,
  },
  [RecipeName.ProduceReinforcedConcrete]: {
    name: RecipeName.ProduceReinforcedConcrete,
    inputs: [
      { resourceType: ResourceType.Cement, amount: 2 },
      { resourceType: ResourceType.Sand, amount: 3 },
      { resourceType: ResourceType.Stone, amount: 2 },
      { resourceType: ResourceType.Steel, amount: 2 },
      { resourceType: ResourceType.Minerals, amount: 0.5 },
      { resourceType: ResourceType.Chemicals, amount: 0.25 },
      { resourceType: ResourceType.Water, amount: 2 },
      { resourceType: ResourceType.Electricity, amount: 2 },
    ],
    outputs: [{ resourceType: ResourceType.ReinforcedConcrete, amount: 7 }],
    requiredWork: 2.6,
    conditionWearMultiplier: 1.3,
  },
  [RecipeName.ProduceConstructionMaterials]: {
    name: RecipeName.ProduceConstructionMaterials,
    inputs: [
      { resourceType: ResourceType.Bricks, amount: 2 },
      { resourceType: ResourceType.ReinforcedConcrete, amount: 1 },
      { resourceType: ResourceType.Steel, amount: 1 },
      { resourceType: ResourceType.Sand, amount: 1 },
      { resourceType: ResourceType.Cement, amount: 1 },
      { resourceType: ResourceType.Chemicals, amount: 0.1 },
      { resourceType: ResourceType.Plastic, amount: 0.2 },
      { resourceType: ResourceType.Electricity, amount: 2 },
    ],
    outputs: [{ resourceType: ResourceType.ConstructionMaterials, amount: 8 }],
    requiredWork: 5.2,
    conditionWearMultiplier: 1.5,
  },
  [RecipeName.BakeCake]: {
    name: RecipeName.BakeCake,
    inputs: [
      { resourceType: ResourceType.Grain, amount: 1 },
      { resourceType: ResourceType.Eggs, amount: 0.5 },
      { resourceType: ResourceType.Electricity, amount: 2 },
      { resourceType: ResourceType.Water, amount: 2 },
    ],
    outputs: [{ resourceType: ResourceType.Cake, amount: 4 }],
    requiredWork: 0.39,
    conditionWearMultiplier: 1,
  },
  [RecipeName.BakePremiumCake]: {
    name: RecipeName.BakePremiumCake,
    inputs: [
      { resourceType: ResourceType.Grain, amount: 1 },
      { resourceType: ResourceType.Eggs, amount: 0.5 },
      { resourceType: ResourceType.Fruit, amount: 1 },
      { resourceType: ResourceType.Milk, amount: 1 },
      { resourceType: ResourceType.Electricity, amount: 2 },
      { resourceType: ResourceType.Water, amount: 2 },
    ],
    outputs: [{ resourceType: ResourceType.PremiumCake, amount: 4 }],
    requiredWork: 0.52,
    conditionWearMultiplier: 1.1,
  },
  [RecipeName.BakeMeatPie]: {
    name: RecipeName.BakeMeatPie,
    inputs: [
      { resourceType: ResourceType.Grain, amount: 1 },
      { resourceType: ResourceType.Meat, amount: 1 },
      { resourceType: ResourceType.Water, amount: 1 },
      { resourceType: ResourceType.Electricity, amount: 2 },
    ],
    outputs: [{ resourceType: ResourceType.MeatPie, amount: 4 }],
    requiredWork: 0.65,
    conditionWearMultiplier: 1.2,
  },
  [RecipeName.ManualPumping]: {
    name: RecipeName.ManualPumping,
    inputs: [],
    outputs: [{ resourceType: ResourceType.Water, amount: 2 }],
    requiredWork: 0.073,
    conditionWearMultiplier: 0.5,
  },
  [RecipeName.ElectricPumping]: {
    name: RecipeName.ElectricPumping,
    inputs: [{ resourceType: ResourceType.Electricity, amount: 1 }],
    outputs: [{ resourceType: ResourceType.Water, amount: 7 }],
    requiredWork: 0.12,
    conditionWearMultiplier: 0.75,
  },
  [RecipeName.CoalPower]: {
    name: RecipeName.CoalPower,
    inputs: [
      { resourceType: ResourceType.Coal, amount: 0.5 },
      { resourceType: ResourceType.Water, amount: 1 },
    ],
    outputs: [{ resourceType: ResourceType.Electricity, amount: 6 }],
    requiredWork: 0.467,
    conditionWearMultiplier: 1.1,
  },
  [RecipeName.SolarPower]: {
    name: RecipeName.SolarPower,
    inputs: [],
    outputs: [{ resourceType: ResourceType.Electricity, amount: 3 }],
    requiredWork: 0.933,
    conditionWearMultiplier: 0.8,
  },
};

export const RECIPE_DISPLAY_NAMES: Readonly<Record<RecipeName, string>> = {
  [RecipeName.GrowGrain]: 'Grow Grain',
  [RecipeName.BakeBread]: 'Bake Bread',
  [RecipeName.ProduceWater]: 'Produce Water',
  [RecipeName.ProduceElectricity]: 'Produce Electricity',
  [RecipeName.GrowSugar]: 'Grow Sugar',
  [RecipeName.GrowFruit]: 'Grow Fruit',
  [RecipeName.RaiseCattle]: 'Raise Cattle',
  [RecipeName.RaiseSheep]: 'Raise Sheep',
  [RecipeName.RaiseChicken]: 'Raise Chicken',
  [RecipeName.MineIron]: 'Mine Iron',
  [RecipeName.MineCoal]: 'Mine Coal',
  [RecipeName.MineCopper]: 'Mine Copper',
  [RecipeName.QuarrySand]: 'Quarry Sand',
  [RecipeName.QuarryClay]: 'Quarry Clay',
  [RecipeName.QuarryStone]: 'Quarry Stone',
  [RecipeName.QuarryMinerals]: 'Quarry Minerals',
  [RecipeName.MineGold]: 'Mine Gold',
  [RecipeName.ProduceSteel]: 'Produce Steel',
  [RecipeName.ProduceElectricCircuits]: 'Produce Electric Circuits',
  [RecipeName.ProduceChemicals]: 'Produce Chemicals',
  [RecipeName.SynthesizeFertilizer]: 'Synthesize Fertilizer',
  [RecipeName.ProducePlastic]: 'Produce Plastic',
  [RecipeName.ProduceSilicon]: 'Produce Silicon',
  [RecipeName.ProduceAdvancedComponents]: 'Produce Advanced Components',
  [RecipeName.AssembleIndustrialMachines]: 'Assemble Industrial Machines',
  [RecipeName.ProduceBricks]: 'Produce Bricks',
  [RecipeName.ProduceCement]: 'Produce Cement',
  [RecipeName.ProduceReinforcedConcrete]: 'Produce Reinforced Concrete',
  [RecipeName.ProduceConstructionMaterials]: 'Produce Construction Materials',
  [RecipeName.BakeCake]: 'Bake Cake',
  [RecipeName.BakePremiumCake]: 'Bake Premium Cake',
  [RecipeName.BakeMeatPie]: 'Bake Meat Pie',
  [RecipeName.ManualPumping]: 'Manual Pumping',
  [RecipeName.ElectricPumping]: 'Electric Pumping',
  [RecipeName.CoalPower]: 'Coal Power',
  [RecipeName.SolarPower]: 'Solar Power',
};

export function getRecipeDisplayName(recipeName: RecipeName): string {
  return RECIPE_DISPLAY_NAMES[recipeName];
}

export function getRecipe(recipeName: RecipeName): Recipe {
  return ALL_RECIPES[recipeName];
}
