export const MARKET_DEFAULT_QUALITY = 1;
export const MARKET_DIFFUSION_DIVISOR = 1_000;
export const MARKET_SALES_CONTRACT_PREMIUM = 1.2;
export const MARKET_AUTOSELL_DEFAULT_MAX_PER_MINUTE = 50;
export const MARKET_AUTOSELL_DEFAULT_MIN_KEEP = 0;
export const MARKET_AUTOSELL_DEFAULT_MIN_PRICE = 0;
export const MARKET_AUTOBUY_DEFAULT_MAX_PRICE_MULTIPLIER = 2;
